### ISSUE TITLE
summary function for reporting

### ISSUE THREAD

**Issue by soumyaray** [sem-in-r/seminr#10]

**Comment by NicholasDanks** [comment]
addressed by branch summarize -

**Comment by singhmanish2999** [comment]
Dear Sir /Mam,
I am getting an error while using summary function on my seminr model as follows. However, it's working fine on your model.

> summary(phd_pls)
Error in seminr_model$outer_weights[mmMatrix[mmMatrix[, "construct"] ==  : 
  subscript out of bounds
> summary(mobi_pls)

 Total Iterations: 7
Path Coefficients:
             Expectation Satisfaction Loyalty Quality Value Complaints
R^2                0.255        0.864   0.735   0.311 0.345      0.353
AdjR^2             0.252        0.862   0.732   0.308 0.340      0.351
Image              0.505        0.207  -0.018       .     .          .
Expectation            .        0.069       .   0.557 0.052          .
Quality                .        0.571       .       . 0.557          .
Value                  .        0.222       .       .     .          .
Satisfaction           .            .   0.895       .     .      0.594
Complaints             .            .  -0.041       .     .          .


Thanks

Regards
