### ISSUE TITLE
an error while using summary function

### ISSUE THREAD

**Issue by singhmanish2999** [sem-in-r/seminr#130]
Dear Sir /Mam,
I am getting an error while using summary function on my seminr model as follows. However, it's working fine on your model.

summary(phd_pls)
Error in seminr_model$outer_weights[mmMatrix[mmMatrix[, "construct"] == :
subscript out of bounds
summary(mobi_pls)

Total Iterations: 7
Path Coefficients:
Expectation Satisfaction Loyalty Quality Value Complaints
R^2 0.255 0.864 0.735 0.311 0.345 0.353
AdjR^2 0.252 0.862 0.732 0.308 0.340 0.351
Image 0.505 0.207 -0.018 . . .
Expectation . 0.069 . 0.557 0.052 .
Quality . 0.571 . . 0.557 .
Value . 0.222 . . . .
Satisfaction . . 0.895 . . 0.594
Complaints . . -0.041 . . .

Thanks

Regards

**Comment by singhmanish2999** [comment]
Dear Sir/Mam,
A similar kind of error report is coming out when fquare to be calculated for a mediating variable "KnowTech" and dependent variable "KnowShare".

fSquared(phd_pls, "OCTAPACE", "KnowShare")
[1] 0.4046501
> fSquared(phd_pls, "KnowTech", "KnowShare")
Error in seminr_model$outer_weights[mmMatrix[mmMatrix[, "construct"] ==  : 
  subscript out of bounds
> fSquared(phd_pls, "Lead3", "OCTAPACE")
[1] 0.001482841
Regards

**Comment by soumyaray** [comment]
Thanks for bring it to our attention @singhmanish2999 

We will likely need more information about your model and data to resolve this issue.  Could you send me an email (you can find it in my profile at https://github.com/soumyaray ) so that we can  share relevant information?

**Comment by soumyaray** [comment]
Greetings @singhmanish2999 kindly let me know if this issue persists or else I will close it soon.

**Comment by singhmanish2999** [comment]
hi
The problem still remains..
I am trying to solve it.

**Comment by soumyaray** [comment]
Hi @singhmanish2999 -- we can help!  Feel free to share any information (such as your code) that we can use to help you resolve it. And feel free to contact us privately if you need. If we don't hear back in some time, we will have to close the issue.

**Comment by NicholasDanks** [comment]
Related issue:

**Comment by NicholasDanks** [comment]
Dear All

Thank you very kindly for your contribution to improving the SEMinR package and as always we value your feedback.
Your feedback has helped us to identify a bug in the code that calculates fSquared for structural model paths. 
Essentially the bug is this: When there is a single path, the code tries to calculate the model parameters when that path is removed, and there are no resulting paths. 
To fix this, we have implemented a line of code that gives a warning that fSquared is not able to be computed on models with a single structural parameter.

**Comment by NicholasDanks** [comment]
To those following this Issue. The bug is patched and we are testing and deploying, but this might take a while. In the interim please download the patched version:
```install.packages("devtools")
library(devtools)
install_github(repo = "https://github.com/sem-in-r/seminr/", ref = "f_square_bug")```
This should install the bumped version 1.0.2 with the patch. Let us know if you have any issues. Thanks again.

**Comment by NicholasDanks** [comment]
@ All. We will add some features soon, and bump the version of the package. We will bundle this bugfix with that version bump.
