### ISSUE TITLE
Disparity with SmartPLS

### ISSUE THREAD

**Issue by stevenhurwitt** [sem-in-r/seminr#131]
I saw on the SmartPLS forum that this package is tested and compared to SmartPLS, however I'm getting different results using each method for the mobi dataset.

![mobi_path_coef_seminr](https://user-images.githubusercontent.com/7502272/79495324-0d463080-7fea-11ea-9dcf-6f4c55912921.PNG)
![smartpls_mobi_data](https://user-images.githubusercontent.com/7502272/79495326-0ddec700-7fea-11ea-95b2-a468e9c042b1.PNG)

**Comment by stevenhurwitt** [comment]
interesting to note that the SmartPLS results seem to (mostly) match up with the semPLS results [here](https://www.researchgate.net/publication/267204270_semPLS_Structural_Equation_Modeling_Using_Partial_Least_Squares)

**Comment by soumyaray** [comment]
Hi @stevenhurwitt -- thanks for your feedback.  Can I ask for the SEMinR code you are using?

**Comment by stevenhurwitt** [comment]
thanks for this, I didn’t even think about the differences between those. I’ll have to tweak the model and play with it. I was just using the code in the docs which mixes mode_a and mode_b for different variables

**Comment by soumyaray** [comment]
Sure @stevenhurwitt -- I'll keep this issue open for a while longer. Please report back whether you resolve it or if it continues to be an issue.

**Comment by stevenhurwitt** [comment]
![mobie_path_coef_seminr_2](https://user-images.githubusercontent.com/7502272/79811228-d437f400-833a-11ea-8eff-b2350c1ae991.PNG)

got it! using the following code indeed matches up with the path coefficients and outer loadings:

`#create measurement model matrix
mobi_mm <- constructs(
  composite("Image",         multi_items("IMAG", 1:5), weights = mode_A),
  composite("Expectation",   multi_items("CUEX", 1:3), weights = mode_A),
  composite("Quality",       multi_items("PERQ", 1:7), weights = mode_A),
  composite("Value",         multi_items("PERV", 1:2), weights = mode_A),
  composite("Satisfaction", multi_items("CUSA", 1:3), weights = mode_A),
  composite("Complaints",   single_item("CUSCO"), weights = mode_A),
  higher_composite("HOC", c("Value", "Satisfaction"), orthogonal, mode_A),
  interaction_term(iv = "Image", moderator = "Expectation", method =  orthogonal, weights = mode_A),
  composite("Loyalty",      multi_items("CUSL", 1:3), weights = mode_A)
)

#create structural model
mobi_sm <- relationships(
  paths(from = "Image",        to = c("Expectation", "Satisfaction", "Loyalty")),
  paths(from = "Expectation",  to = c("Quality", "Value", "Satisfaction")),
  paths(from = "Quality",      to = c("Value", "Satisfaction")),
  paths(from = "Value",        to = c("Satisfaction")),
  paths(from = "Satisfaction", to = c("Complaints", "Loyalty")),
  paths(from = "Complaints",   to = "Loyalty")
)

#model estimation
mobi_pls <- estimate_pls(data = mobi,
                         measurement_model = mobi_mm,
                         structural_model = mobi_sm,
                         inner_weights = path_weighting)`

Thanks for your help with this!

**Comment by soumyaray** [comment]
Good stuff!  Nice use of higher order constructs as well. Let us know if you have any other concerns or questions.

**Comment by stevenhurwitt** [comment]
Hey, 

I'm running into this issue again. I'm running my code with composite factors using mode A:

![df9_pls_syntax](https://user-images.githubusercontent.com/7502272/81633482-798e3700-93d2-11ea-99fa-3eff974fe31f.PNG)

But the results are slightly different than what I get using SmartPLS. Results from seminr:

![df9_pls_output](https://user-images.githubusercontent.com/7502272/81633510-8dd23400-93d2-11ea-9436-5d1fb1d4b768.PNG)

Results from SmartPLS:

![df9_full_sim_smart_pls](https://user-images.githubusercontent.com/7502272/81633521-94f94200-93d2-11ea-90ce-f29348d35a26.PNG)

Though they are sometimes similar, which is strange. Could it be a setting I need to change in SmartPLS? Additionally is there a way to calculate Chronbach's Alpha, CR, AVE, etc. using seminr? I can get it from SmartPLS, but as the results aren't lining up I'm guessing these values would be slightly different.

Dataset is also attached.

[df9.zip](https://github.com/sem-in-r/seminr/files/4613138/df9.zip)

**Comment by soumyaray** [comment]
Thanks for the update. We’re looking into it. First, can i ask if “Self” is the same as feedback self-efficacy? it seems to have three outgoing paths in the SmartPLS model but only one in the seminr model?

**Comment by NicholasDanks** [comment]
Hi Stephen 

Great to hear from you again. 
I ran the following code:
```data1 <- read.csv(file = "df9.csv")
#create measurement model matrix
mobi_mm <- constructs(
  composite("Optimism",         multi_items("opt", 1:3)),
  composite("Perspective",      multi_items("pt", 1:5)),
  composite("Self",             multi_items("fse", 1:3)),
  composite("TeamPerf",         multi_items("teamperf", 1:3)),
  composite("ICT",              multi_items("ict", 1:3)),
  composite("IT",               multi_items("ITexp", 1:3)),
  composite("Info",             multi_items("infint", 1:3)),
  composite("Leader",           multi_items("lmx", 1:7))
)

#create structural model
mobi_sm <- relationships(
  paths(from = "Optimism",        to = c("Leader", "Self")),
  paths(from = "Perspective",     to = c("Leader", "Self", "ICT","IT")),
  paths(from = "Info",            to = c("Leader", "Self", "ICT","IT")),
  paths(from = "Self",            to = c("Leader", "TeamPerf", "IT")),
  paths(from = "Leader",          to = c("TeamPerf","Self")),
  paths(from = "ICT",             to = c("IT")),
  paths(from = "IT",              to = "TeamPerf")
)

#model estimation
mobi_pls <- estimate_pls(data = data1,
                         measurement_model = mobi_mm,
                         structural_model = mobi_sm,
                         inner_weights = path_weighting)
mobi_pls$outer_loadings```

I have achieved the same results as:

<img width="959" alt="Screen Shot 2020-05-12 at 9 23 06 PM" src="https://user-images.githubusercontent.com/17057395/81696651-c89da000-9496-11ea-9243-49357517dd15.png">

Quick one: When sharing code, it is best practice to allow it to be copied and pasted. I usually do this by using the "```"

My conclusion is it's probably a model misspecification in your code.
Hope this helps.

Kind regards,

**Comment by stevenhurwitt** [comment]
thanks y'all, looks like it is!

**Comment by soumyaray** [comment]
> Additionally is there a way to calculate Chronbach's Alpha, CR, AVE, etc. using seminr?

Hi @stevenhurwitt -- just to followup on this question, you can get reliability/validity metrics of your PLS model estimation by calling the `summary()` function and giving it your estimated PLS model.

```R
df_pls <- estimate_pls(...)
summary(df_pls)
```

Note that we supply AVE, and CR as rhoC or rhoA. We don't supply Cronbach Alpha and you will find recent literature discouraging its use (let us know if you need some references).

For even more summary statistics, capture the summary object in a variable and inspect its contents (using `$` after its name).

```R
df_summary <- summary(df_pls)
df_summary$...
```

You will find other useful validation metrics, including f-squares, HTMT, etc.

**Comment by stevenhurwitt** [comment]
thanks for this, wasn't sure if i was just missing Cronbach's Alpha or what - thanks for the info!
