### ISSUE TITLE
"Subscript out of bounds" error in summary()

### ISSUE THREAD

**Issue by Quadrophonia** [sem-in-r/seminr#142]
I'm really liking SEMinR! However, I'm having a similar problem to #130 and it persists even though I have installed the patch recommended in that issue ticket. 

When I build and run a seminr model, I get the following error:
```R
> pls_model <- estimate_pls(data = plsdata, 
+                           measurement_model = measurements, 
+                           structural_model = structure)
Generating the seminr model
All 245 observations are valid.
> summary(pls_model)
Error in seminr_model$outer_weights[mmMatrix[mmMatrix[, "construct"] ==  : 
  subscript out of bounds
```
This error appears even though I'm only calling the model summary function (i.e. not just the f-square call). The data and model work fine in SmartPLS, so I don't think it's a data issue. 

The error means that the model summary is never presented. However, I can bootstrap the model successfully:

```R
> boot_estimates <- bootstrap_model(pls_model, 
+                                   nboot = 1000, 
+                                   cores = 2)
Bootstrapping model using seminr...
SEMinR Model successfully bootstrapped> summary(boot_estimates)
Bootstrap resamples: 1000

Bootstrapped Structural Paths:...
```
I'm running SEMinR 1.0.2 under RStudio Version 1.2.5042 "Double Marigold", Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36

**Comment by soumyaray** [comment]
Hi there! Thanks for the feedback and I'm delighted you are enjoying SEMinR -- we will look into this issue right away. Could I ask if you could share your data and code for us to reproduce the problem?  We will keep both confidential and delete them as soon as we are done reproducing and fixing the issue.  You may email me at: soumya.ray AT gmail.com 

If you cannot share them, we will nonetheless try to work the problem out at our end.

**Comment by Quadrophonia** [comment]
Hi Soumya
Thanks for your very quick response! I have emailed you the materials you've requested. Thanks!!

**Comment by NicholasDanks** [comment]
All tests passing and bug fixed. Thank you very much @Quadrophonia for assisting us in improving SEMinR. We hope that you find the package useful.

**Comment by NicholasDanks** [comment]
We have now merged the bugfix142 branch to the develop branch. We will bump the version very soon. In the interim ```devtools::install_github("https://github.com/sem-in-r/seminr", ref = "develop"``` can be used to install the patched SEMinR. Thank you for helping us to spot and fix this bug.

**Comment by soumyaray** [comment]
@Quadrophonia We closed this issue and want to explicitly confirm that any data/code you supplied us for the resolution of this bug has been deleted. Please note that a soon upcoming release of SEMinR will also support CBSEM (ala LISREL/AMOS) estimation if that should interest you.

You can follow developments on SEMinR either at this Github repo or on our FB group:
https://www.facebook.com/groups/seminr
