### ISSUE TITLE
Cant locate SEMinR v. 1.1.0

### ISSUE THREAD

**Issue by fawad83** [sem-in-r/seminr#153]
I am trying to update SEMinR package but it gives me the following issues when i try to use install.packages("seminr")

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

Now i have downloaded RTools from the website below and installed it but still same issue
https://cran.r-project.org/bin/windows/

I also downloaded the Zip file for GitHub but when i try to install, it says the shows the following in Red and doesnt do anything
https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/kfls_/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

Also under this link the package is still old, its 1.0.2
https://cran.r-project.org/web/packages/seminr/index.html

**Comment by soumyaray** [comment]
Hi Fawad, so are we correct in assuming that RTools did not install properly? Please close and restart RStudio after installing RTools. If there was an an error message during installing RTools, please provide it here.

We know there is an issue with the latest v1.1.0 not showing up -- it should resolve over the next couple of days.

**Comment by fawad83** [comment]
Dear Dr. Soumya

RTools was installed properly.  There was no error. I even restarted my system. 

I have tried to update it from Packages section by search for SEMinR alsoi downloaed one from GitUp and tried to install it manually but i get the following and nothing happens. It stops, while with other packages i did get this error but they moved on and packages were updated, where i clicked on updating packages 

> install.packages("C:/Users/kfls_/Downloads/seminr-master.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/kfls_/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

**Comment by soumyaray** [comment]
Fawad, did you resolve this issue yet?  I saw you faced another bug so I assume you have seminr working somehow.  v1.1.0 is up on cran as of last night (its release was delayed -- sorry) so please try to update again if you need to.

**Comment by fawad83** [comment]
Dear Prof. 

I havent tried that fix of other bug, like with multiple indicators (will do that today).
and Yes now the package is updated. I have SemInR v 1.1.0

Really thankful to you for your patience and support. 

Thanks.

**Comment by soumyaray** [comment]
Great!
