### ISSUE TITLE
how to get the blindfolding-based crossvalidated redundancy measure Q2

### ISSUE THREAD

**Issue by maoyimin** [sem-in-r/seminr#156]
When I use the seminr 1.1.0, I can not obtain the blindfolding-based crossvalidated redundancy measure Q2. Can you tell me how to get the value of this assessment criteria? Thanks.

**Comment by soumyaray** [comment]
Hi @maoyimin, thanks for using SEMinR and submitting this issue!

As of now we do not support Q2.  I don't want to speak for anyone other contributor/collaborator, but I personally do not think we will offer Q2 in the near future, as I have some methodological qualms about the method. Please see Appendix C of Shmueli et al. (2016) for a critique of Q2 in PLS path models. I have not heard any rebuttal of that critique yet, but am open to it.

Kindly let me know if you have any further questions or comments on this issue.

Shmueli, G., Ray, S., Estrada, J. M. V., & Chatla, S. B. (2016). The elephant in the room: Predictive performance of PLS models. Journal of Business Research, 69(10), 4552-4564.
https://www.sciencedirect.com/science/article/abs/pii/S0148296316301217

**Comment by maoyimin** [comment]
Thank you for your answer @soumyaray 
I think your paper can give me a better understanding of the predictive performance of pls models.
And, I have another question: I can not find the values of the Cronbach’s alpha when I summary the estimated sem models. 
I wonder why don't you include it in the summary functions when calculating the reliability scores. 
Thanks.

**Comment by soumyaray** [comment]
Hi @maoyimin, excellent question once again.  But could I kindly ask you to open up a new issue for this new question?  It would greatly help future users/maintainers to search and find the question and response!
