### ISSUE TITLE
Provide the Cronbach’s alpha

### ISSUE THREAD

**Issue by maoyimin** [sem-in-r/seminr#158]
Prof. Ray,

I have another question: I can not find the values of the Cronbach’s alpha when I summary the estimated sem models. Although I can obtain the the Cronbach’s alpha by using other packages, like psy r package, I really hope that I can do it within the application of seminr. I wonder why don't you include it in the summary functions when calculating the reliability scores.

Thanks.

**Comment by soumyaray** [comment]
Hi @maoyimin, thank you for your careful observation.

Cronbach alpha makes some assumptions that all the items of a construct reflect the construct equally well, and so all the items should have the same loading. If this is not true, then Cronbach alpha will underestimate reliability. Composite Reliability (CR, or rhoC) is more favored nowadays as it allows your items to be slightly different in how effectively they represent your construct. We treat Cronbach Alpha as a lower bound of reliability and Composite Reliability as a more accurate assessment. In practice, we usually find our items have fairly similar loadings and so the two metrics do not differ by that much. While Cronbach alpha may have particularly good uses, we believe that it should not be the first choice for constructs in SEM.

Please see the papers below for more details on the issues with Cronbach Alpha and the difference between the two metrics. You may cite them to defend your choice of metric.

Raykov, T. (1998). Coefficient alpha and composite reliability with interrelated nonhomogeneous items. Applied psychological measurement, 22(4), 375-385.

Peterson, R. A., & Kim, Y. (2013). On the relationship between coefficient alpha and composite reliability. Journal of Applied Psychology, 98(1), 194–198. https://doi.org/10.1037/a0030767

**Comment by maoyimin** [comment]
@soumyaray  thank you for your nice response. I will read the papers you suggested, so as to get a deeper understanding of Cronbach alpha. 

I think Seminr is a user-friendly package to anyone who attempts to use SEM models.

**Comment by soumyaray** [comment]
Thanks @maoyimin -- best of luck on your research and don't hesitate to reach out to us.
