### ISSUE TITLE
Error in summary(): "Error in new_model$construct_scores[, dimensions] : Subscript out of bounds" 

### ISSUE THREAD

**Issue by Lilikon** [sem-in-r/seminr#161]
Hi everyone, first of all a huge thank you for your work on this package. I really enjoy working with SEMinR.

Unfortunately, I face an issue with the summary() function similar to issue #142 and it has not resolved with the update to V1.1.0: 
 ```r
> modelcc <- estimate_pls(datacc, mmcc, smcc)
Generating the seminr model
Generating the seminr model
All 117 observations are valid.
All 117 observations are valid.
> summary(modelcc)
Error in new_model$construct_scores[, dimensions] : 
  Subscript out of bounds
```

I am unsure why  it seems to be generating the model twice in the output. As in the previous issue, bootstrapping the model works just fine.

I am using SEMinR 1.1.0, R version 4.0.2, RStudio Version 1.3.959 "Middlemist Red".

**Comment by Lilikon** [comment]
Hi Nick,
thank you so much for your help. The model runs now! I will close the issue.

**Comment by NicholasDanks** [comment]
@Lilikon Please note that there were some bugs in that patch release. I would suggest that you rerun the following and download the now stable beta version:
```
install.packages("devtools")
devtools::install_github(repo = "sem-in-r/seminr", ref = "Primer_preparation")
```
Thanks and keep modeling!

**Comment by adrotar22** [comment]
Hi there, I have a similar issue. can you please help?

**Comment by soumyaray** [comment]
@adrotar22 could you update to the latest version of SEMinR and see if it resolves the issue?

**Comment by adrotar22** [comment]
I've only installed it recently, so should be the latest ? I installed
seminr a week ago...
