### ISSUE TITLE
Provide loadings, weights and reliability for lower-order constructs

### ISSUE THREAD

**Issue by Lilikon** [sem-in-r/seminr#162]
Hi all,

thank you again for your work on this package and your quick help with my last issue.

I am still working with higher_composite constructs and have run into the following problem: When I estimate a PLS model with higher_composite constructs, loadings, weights and reliability are only reported for the paths between the higher-order construct and its associated lower-order constructs. I cannot seem to access loadings, weights or reliability for the paths between the lower-order constructs and their associated items.

Please take a look at this example using the mobi dataset:

```r
mm <- constructs(
  composite("Image",         multi_items("IMAG", 1:5)),
  composite("Satisfaction",  multi_items("CUSA", 1:3)),
  composite("Expectation",   multi_items("CUEX", 1:3)),
  composite("Quality",       multi_items("PERQ", 1:7)),
  composite("Value",         multi_items("PERV", 1:2)),
  higher_composite("HOC", c("Value", "Quality"), mode_B)
  )

sm <- relationships(
  paths(from = c("HOC", "Expectation"),        
        to = c("Image", "Satisfaction")
)

testmodel <- estimate_pls(mobi, mm, sm)
modelsummary <- summary(testmodel)
modelsummary$reliability
```
The output for this is:

```r
            alpha rhoC  AVE   rhoA 
HOC         0.739 0.881 0.788 0.811
Expectation 0.452 0.731 0.48  0.47 
Image       0.723 0.819 0.478 0.738
```
It reports the reliability statistics for the "HOC", "Expectation" and "Image", but not for "Value" or "Quality". 
Analogously, the output for modelsummary$loadings is:

```r
          HOC Expectation Image
IMAG1   0.000       0.000 0.752
IMAG2   0.000       0.000 0.606
IMAG3   0.000       0.000 0.583
IMAG4   0.000       0.000 0.774
IMAG5   0.000       0.000 0.722
CUEX1   0.000       0.747 0.000
CUEX2   0.000       0.753 0.000
CUEX3   0.000       0.561 0.000
Value   0.844       0.000 0.000
Quality 0.929       0.000 0.000
```
There is no output for the items associated with Value and Quality, i.e. PERQ1-PERQ7, PERV1  and PERV2.. The output for modelsummary$weights is similar.

I think access to this "lower level" measurement model data would be highly valuable for rigorous evaluation of the measurement model.  If there is already a possibility to access this data, please excuse the trouble. Maybe you can point me in the right direction?

Thank you in advance.

**Comment by NicholasDanks** [comment]
Dear @Lilikon 

Thank you very much for pointing out another very important issue with SEMinR. On the face of it I agree with you that the "lower level" measurement model evaluation is also highly important. Please allow myself and @soumyaray to discuss and devise a solution a for this. 

We really appreciate your ongoing support and investigation of the package - you are providing invaluable feedback that continues to improve the quality.

Kind regards,
Nick

**Comment by NicholasDanks** [comment]
Dear @Lilikon 

I'd like to thank you again for bringing up this important issue. This topic requires a little more thinking on how to report results and how to edit the output objects.

**Comment by Lilikon** [comment]
Dear Nick,

thank you so much for your quick response and the patch. It works great!

Sincerely,
Lilian

**Comment by NicholasDanks** [comment]
Hi Lilian

I hope you are well. Is this issue resolved? 
If so, please do close the issue.

Happy modeling!

**Comment by Lilikon** [comment]
Dear Nick,

sorry for not closing the issue thus far. I was under the assumption that the patch was only a preliminary solution - even though it worked very well. One exception to that: Even with the patch, it is still not possible to access information on the bootstrap results for the first order model.

If you would like, I can still close the issue and open a new one concerning the access to bootstrap information.

Sincerely,
Lilian

**Comment by NicholasDanks** [comment]
Dear Lilian

Thanks for the reply. What would you like to see regarding the first stage? The first stage is just to generate the construct scores for the second stage.
Please do let us know if we can improve the reporting.
Thanks!

Kind regards,

Nicholas Patrick Danks
PhD.




On Dec 2, 2020, at 1:20 PM, Lilikon <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear Nick,

sorry for not closing the issue thus far. I was under the assumption that the patch was only a preliminary solution - even though it worked very well. One exception to that: Even with the patch, it is still not possible to access information on the bootstrap results for the first order model.

If you would like, I can still close the issue and open a new one concerning the access to bootstrap information.

Sincerely,
Lilian

**Comment by Lilikon** [comment]
Dear Nicholas,

allow me to elaborate. In a "simple" PLS model, SEMinR provides data on loadings, weights and reliability for the original estimate measurement model, i.e., the relation between constructs and indicators as defined by the composite specification. With the patch, I can now also access loadings, weights and reliability for the indicators measuring the first-order (or lower-order) constructs. Using the same example as above:

```r
mm <- constructs(
  composite("Image",         multi_items("IMAG", 1:5)),
  composite("Satisfaction",  multi_items("CUSA", 1:3)),
  composite("Expectation",   multi_items("CUEX", 1:3)),
  composite("Quality",       multi_items("PERQ", 1:7)),
  composite("Value",         multi_items("PERV", 1:2)),
  higher_composite("HOC", c("Value", "Quality"), mode_B)
  )

sm <- relationships(
  paths(from = c("HOC", "Expectation"),        
        to = c("Image", "Satisfaction"))
  )

testmodel <- estimate_pls(mobi, mm, sm)
modelsummary <- summary(testmodel)
modelsummary$reliability

# Added functionality with the patch
fsmodelsummary <- summary(testmodel$first_stage_model)
fsmodelsummary$reliability
fsmodelsummary$loadings
fsmodelsummary$weights

# For loadings and weights, the output is identical when using
testmodel$first_stage_model$outer_loadings
testmodel$first_stage_model$outer_weights
```

With these new functions, I am now able to access the original estimate information on this part of  the measurement model, which is great. However, if I bootstrap the model, I can only access information on mean, SD, t-value and confidence interval for the measurement model concerning the relationships between "simple" constructs and indicators or higher-order and lower-order constructs, not between lower-order constructs and their indicators. This also applies to HTMT information.

Using the same example:

```r
bootmodel <- bootstrap_model(testmodel, nboot = 5000)
bootsummary<- summary(bootmodel)
bootsummary$bootstrapped_loadings
bootsummary$bootstrapped_HTMT
```
gives you the following output:

```r
> bootsummary$bootstrapped_loadings
                        Original Est. Bootstrap Mean Bootstrap SD T Stat. 2.5% CI 97.5% CI
IMAG1  ->  Image                0.753          0.750      0.03620   20.79   0.670    0.811
IMAG2  ->  Image                0.606          0.604      0.05733   10.57   0.482    0.705
IMAG3  ->  Image                0.583          0.583      0.06106    9.55   0.452    0.690
IMAG4  ->  Image                0.774          0.773      0.04422   17.51   0.672    0.841
IMAG5  ->  Image                0.720          0.721      0.03812   18.89   0.638    0.787
CUSA1  ->  Satisfaction         0.799          0.799      0.02974   26.87   0.735    0.849
CUSA2  ->  Satisfaction         0.853          0.852      0.02135   39.95   0.807    0.890
CUSA3  ->  Satisfaction         0.846          0.846      0.02047   41.32   0.801    0.881
CUEX1  ->  Expectation          0.755          0.751      0.05350   14.11   0.631    0.837
CUEX2  ->  Expectation          0.732          0.728      0.07455    9.82   0.554    0.846
CUEX3  ->  Expectation          0.580          0.578      0.07935    7.31   0.405    0.715
Value  ->  HOC                  0.851          0.850      0.03274   26.00   0.774    0.903
Quality  ->  HOC                0.924          0.925      0.00819  112.77   0.908    0.940
> bootsummary$bootstrapped_HTMT
                              Original Est. Bootstrap Mean Bootstrap SD T Stat. 2.5% CI 97.5% CI
HOC  ->  Expectation                  0.892          0.902       0.1121    7.96   0.688    1.130
HOC  ->  Image                        0.964          0.970       0.0543   17.77   0.868    1.080
HOC  ->  Satisfaction                 1.033          1.036       0.0414   24.94   0.960    1.123
Expectation  ->  Image                0.888          0.899       0.1064    8.35   0.700    1.120
Expectation  ->  Satisfaction         0.865          0.873       0.0963    8.98   0.695    1.069
Image  ->  Satisfaction               0.910          0.913       0.0356   25.56   0.842    0.981
```

The output for bootsummary$bootstrapped_weights is similar to bootsummary$bootstrapped_loadings.
But the same output is not available for the first-stage model, i.e., for the indicators associated with Value (PERQ1-PERQ7) and Quality (PERV1 and PERV2). The following functions all produce the same output, which is, as I understand, the output associated with the original estimate model.

```r
fsbootsummary <- summary(bootmodel$first_stage_model)
# Loadings
fsbootsummary$loadings
fsmodelsummary$loadings
bootmodel$first_stage_model$outer_loadings
testmodel$first_stage_model$outer_loadings
```

The same is true for outer weights, and HTMT information for those first-stage relationships cannot be accessed from the bootstrapped model at all.

As for why I think reporting this information is important, I understand that rigorously evaluating all parts of the measurement model is important, even with higher-order construct. Following the recommendations of Hair et al.'s primer on PLS-SEM (2017), this requires data on the HTMT bootstrap confidence interval for the evaluation of reflectively measured indicators, and data on the bootstrap significance of weights and loadings for the evaluation of formatively measured indicators.

From the information in the reference manual, I assume that SEMinR estimates higher-order models using the disjoint two-stage approach. As I understand it, the "How to specify, estimate, and validate higher-order constructs in PLS-SEM" paper by Sarstedt et al. (2019, https://doi.org/10.1016/j.ausmj.2019.05.003) provides more rationale on why the first-stage measurement model should be separately evaluated.

(Additionally, when reporting model results, I personally would find it nice to display significance information for all parts of the model.)

Thank you so much for your support thus far. I am looking forward to your thoughts on the necessity of accessing this data!

Sincerely,
Lilian

**Comment by NicholasDanks** [comment]
Dear Lilian

Thank you again for the ongoing assistance. 
I believe we have now made some changes and updates that address (mostly) what you are in need of. 

I refer to the Table 7 in the article: M. Sarstedt, J.F. Hair Jr and J.-H. Cheah et al., How to specify, estimate, and validate higher-order constructs in PLS-SEM, Australasian Marketing Journal, https://doi.org/10.1016/j.ausmj.2019.05.003

*Measurement Model evaluation:*
- Apply standard model evaluation criteria on the measurement models for the lower-order components
- Interpret the relationships between the higher-order and lower-order components as the measurement model of the higher-order construct: 
-- Reflective-reflective and formative-reflective type higher-order constructs: Interpret the relationships between higher-order and lower-order components as loadings and assess convergent validity, internal consistency reliability, and discriminant validity metrics
-- Reflective-formative and formative-formative higher-order constructs: Interpret the relationships between higher-order and lower-order components as weights and assess convergent validity, collinearity, and the significance and relevance of the weights

*Structural Model Evaluation:*
- Apply standard model evaluation criteria on the structural model
- Do not consider the lower-order components as elements of the structural model (thus HTMT of lower and higher order constructs combined is not necessary and might be incorrect to assess since the LOC should not show discriminant validity from HOC)

This can be performed by doing the following (seminr-pls-higher_order demo file with extra code): 
```
library(seminr)

# Creating measurement mode
# - note: composite() has a default parameter setting of mode A
# - note: items can be a list of names: c("CUEX1", "CUEX2", "CUEX3")
#         which can be constructed quickly as: multi_items("CUEX", 1:3)
mobi_mm <- constructs(
  composite("Image",        multi_items("IMAG", 1:5)),
  composite("Expectation",  multi_items("CUEX", 1:3)),
  composite("Quality",      multi_items("PERQ", 1:7)),
  composite("Value",        multi_items("PERV", 1:2)),
  higher_composite("Satisfaction", dimensions = c("Image","Value"), method = two_stage),
  composite("Complaints",   single_item("CUSCO")),
  composite("Loyalty",      multi_items("CUSL", 1:3))
)

# Creating structural model
# - note, multiple paths can be created in each line
mobi_sm <- relationships(
  paths(from = c("Expectation","Quality"),  to = "Satisfaction"),
  paths(from = "Satisfaction", to = c("Complaints", "Loyalty"))
)

# Estimate the model with the HOC
mobi_pls <- estimate_pls(data = mobi,
                         measurement_model = mobi_mm,
                         structural_model = mobi_sm)

# Access the criteria of the first stage
first_stage_summary <- summary(mobi_pls$first_stage_model)
first_stage_summary

# Access the criteria of the final stage (including first stage weights and loadings)
model_sum <- summary(mobi_pls)
model_sum

# Finally we present all the loadings and weights from both stages in the bootstrap report
boot <- bootstrap_model(mobi_pls, nboot = 500)
sum_boot <- summary(boot)
sum_boot$bootstrapped_loadings
```

This should now resolve your issue, but please do let us know if you need any further features.


Many thanks and happy new year!!
Happy modeling!

Nick

**Comment by Lilikon** [comment]
Hi Nick,

thank you so much for your assistance. I just had the occasion to test your changes on a new dataset and it works like a dream. Therefore, I will now close the issue.

A belated happy new year to you as well and many thanks again!
Lilian
