### ISSUE TITLE
Confidence intervals  for multiple mediation paths 

### ISSUE THREAD

**Issue by DanielMcKayPhD93** [sem-in-r/seminr#164]
Hi there,

Thank you so much for your excellent work on the SEMinR package and for your incredible support over the last year, it is very much appreciated. 

I am hoping to run multiple mediation models, with both serial and parallel mediation components. For example, serial mediation entailing predictor(s) -> mediator 1 -> mediator 2 -> mediator 3 -> outcome(s). Parallel mediation: predictors -> mediators 1, 2, and 3 -> outcome(s). My models will contain both. 

It would be great if a feature could be added which allows for the calculation of confidence intervals for multiple mediation chains, in addition to the single mediation chains already offered. 

Many thanks for your time, it is very much appreciated!

With all best wishes,
Daniel McKay

**Comment by soumyaray** [comment]
Hi @DanielMcKayPhD93 always great to hear from you.  I think what you are asking is very doable.  I might contact you by email to clarify some details. Please accept our apologies for the delay -- @NicholasDanks and I have both been busy with a few things but we are looking into this.

**Comment by NicholasDanks** [comment]
Dear Daniel

My apologies for delay in responding to you.
As always, thank you for your ongoing support and help with improving the package.
I have updated functionality to provide the features you need, but we have not yet updated the version as we are preparing for a new major release. 
For now you can run: 
```
devtools::install_github(repo = "https://github.com/sem-in-r/seminr",ref = "Primer_preparation")
```
to install the beta version from github. You can then use the following code to access the information you want:
```
library(seminr)

# Load the data
corp_rep_data <- corp_rep_data

# Create measurement model ----
corp_rep_mm_ext <- constructs(
  composite("QUAL", multi_items("qual_", 1:8), weights = mode_B),
  composite("PERF", multi_items("perf_", 1:5), weights = mode_B),
  composite("CSOR", multi_items("csor_", 1:5), weights = mode_B),
  composite("ATTR", multi_items("attr_", 1:3), weights = mode_B),
  composite("COMP", multi_items("comp_", 1:3)),
  composite("LIKE", multi_items("like_", 1:3)),
  composite("CUSA", single_item("cusa")),
  composite("CUSL", multi_items("cusl_", 1:3))
)

# Create structural model ----
corp_rep_sm_ext <- relationships(
  paths(from = c("QUAL", "PERF", "CSOR", "ATTR"), to = c("COMP", "LIKE")),
  paths(from = c("COMP", "LIKE"), to = c("CUSA", "CUSL")),
  paths(from = c("CUSA"),         to = c("CUSL"))
)

# Estimate the model ----
corp_rep_pls_model_ext <- estimate_pls(data              = corp_rep_data,
                                       measurement_model = corp_rep_mm_ext,
                                       structural_model  = corp_rep_sm_ext,
                                       missing = mean_replacement,
                                       missing_value = "-99")

# Extract the summary
summary_corp_rep_ext <- summary(corp_rep_pls_model_ext)

# Estimated total effects
summary_corp_rep_ext$total_effects

# Estimated total indirect effects
summary_corp_rep_ext$total_indirect_effects

# Bootstrap the model ----
boot_corp_rep_ext <- bootstrap_model(seminr_model = corp_rep_pls_model_ext,
                                     nboot = 1000,
                                     cores = parallel::detectCores(),
                                     seed = 123)

# Summarize the results of the bootstrap
summary_boot_corp_rep_ext <- summary(boot_corp_rep_ext,
                                     alpha = 0.05)

# Total indirect effects between an antecedent and outcome construct
total_indirect_ci(boot_corp_rep_ext,from = "QUAL", to = "CUSL")

# Confidence interval of a specific indirect effect for up to 4 mediators
confidence_interval(boot_corp_rep_ext, from = "QUAL", through = c("LIKE", "CUSA"), to = "CUSL")
```

This suite of new functions should provide you with all the tools you need for mediator analyses. 

Please let us know if you need anything else and 
Happy Modeling!!

Kind regards,
Nick

**Comment by DanielMcKayPhD93** [comment]
Dear Nicholas, 

Thank you so much for this, I can’t wait to use this next week! I hugely appreciate the time and effort you have both put into this, and helping me!

Take care
Best wishes
Daniel

**Comment by NicholasDanks** [comment]
Dear Daniel

I hope you are well.
Is this issue resolved? If so, please close the issue.

Happy modeling!

**Comment by DanielMcKayPhD93** [comment]
Dear Nicholas,

Many thanks for resolving this issue, it is greatly appreciated. Apologies for not closing the issue sooner and thanks for pointing this out, I am quite a new user of GitHub and never knew to do this.

Thanks for pointing this out, and again for all of your support. :)

With all best wishes,
Daniel
