### ISSUE TITLE
Unable to calculate HOC: reciprocal condition number = 0

### ISSUE THREAD

**Issue by Mo-C1** [sem-in-r/seminr#167]
Hi all,

As mentioned in the facebook post, I am entirely new to R, PLS-SEM and GitHub. So first thanks for putting together this package 👍 

I am trying to build a HOC using the two_stage method, I run into the following problem when trying to estimate the model:

`Error in solve.default(construct_score_cors[c(independant, dependant[i]), :
system is computationally singular: reciprocal condition number = 0`

My model is rather simple, but I'll post the code anyways (including the error code) if that helps:

`#Load Library and Data`
`library(seminr)`

`surveyData <- read.csv2("[...].csv")`

`surveyDataDF <- data.frame (surveyData)`

`#Measurement model definition`

`measurements <- constructs(`

`#Antecedents`
	`reflective("MOPRO",         multi_items("v_", 107:114)),`
	`reflective("MORTN",         multi_items("v_", 115:121)),`

`composite("VDISC",         c("v_38", "v_39", "v_40", "v_45"), weights = mode_B),`
`composite("VCOC",         c("v_41", "v_42", "v_43", "v_44", "v_46", "v_47"), weights = mode_B),`
`composite("VQUAN",           c("v_49", "v_51", "v_54"), weights = mode_B),`
`composite("VBPRI",          c("v_55", "v_56", "v_57"), weights = mode_B),`
`composite("VCOMM",          c("v_61", "v_63", "v_64"), weights = mode_B),`
`composite("VLRNG",          c("v_65", "v_66", "v_68", "v_69"), weights = mode_B),`
`higher_composite("VBS", dimensions = c("VDISC","VCOC","VQUAN","VBPRI","VCOMM","VLRNG"), method = two_stage, weights = mode_B),`
`reflective("SALSPERF",         multi_items("v_", 144:151))
)`

`#Structural model definition`

`structure <- relationships(`

`#paths (from = c("VDISC","VCOC","VQUAN","VBPRI","VCOMM","VLRNG"), to = "SALSPERF"),`
`paths (from = c("MOPRO"), to = "VBS"),`
`paths (from = c("MORTN"), to = "VBS"),`
`paths (from = c("VBS"), to = "SALSPERF")
)`

`print("End of structural model")`

`#Estimate model`

`pls_model <- estimate_pls ( data = surveyDataDF,`
					`measurement_model = measurements,`
					` structural_model = structure)`
`summary(pls_model)`

Any help would be greatly appreciated!

Thank you for your support,
Moritz

**Comment by NicholasDanks** [comment]
Dear Moritz

It's great to hear from you. We're really happy that you are finding our package useful. 
As a first attempt, I made a substitute dataset on which to run your model:
```
library(seminr)

surveyData <- cbind(mobi,mobi[,-c(23,24)])

surveyDataDF <- data.frame (surveyData)
colnames(surveyDataDF) <- c(multi_items("v_", 107:114),
                            multi_items("v_", 115:121),
                            c("v_38", "v_39", "v_40", "v_45"),
                            c("v_41", "v_42", "v_43", "v_44", "v_46", "v_47"),
                            c("v_49", "v_51", "v_54"),
                            c("v_55", "v_56", "v_57"),
                            c("v_61", "v_63", "v_64"),
                            c("v_65", "v_66", "v_68", "v_69"),
                            multi_items("v_", 144:151))

#Measurement model definition

measurements <- constructs(
  
  #Antecedents
  reflective("MOPRO", multi_items("v_", 107:114)),
  reflective("MORTN", multi_items("v_", 115:121)),
  
  composite("VDISC", c("v_38", "v_39", "v_40", "v_45"), weights = mode_B),
  composite("VCOC", c("v_41", "v_42", "v_43", "v_44", "v_46", "v_47"), weights = mode_B),
  composite("VQUAN", c("v_49", "v_51", "v_54"), weights = mode_B),
  composite("VBPRI", c("v_55", "v_56", "v_57"), weights = mode_B),
  composite("VCOMM", c("v_61", "v_63", "v_64"), weights = mode_B),
  composite("VLRNG", c("v_65", "v_66", "v_68", "v_69"), weights = mode_B),
  higher_composite("VBS", dimensions = c("VDISC","VCOC","VQUAN","VBPRI","VCOMM","VLRNG"), method = two_stage, weights = mode_B),
  reflective("SALSPERF", multi_items("v_", 144:151)) )

#Structural model definition

structure <- relationships(
  
  #paths (from = c("VDISC","VCOC","VQUAN","VBPRI","VCOMM","VLRNG"), to = "SALSPERF"),
  paths (from = c("MOPRO"), to = "VBS"),
  paths (from = c("MORTN"), to = "VBS"),
  paths (from = c("VBS"), to = "SALSPERF") )

print("End of structural model")

#Estimate model

pls_model <- estimate_pls ( data = surveyDataDF,
                            measurement_model = measurements,
                            structural_model = structure)
summary(pls_model)
```
Using this substitute dataset I can get your model to estimate - so it seems this is not a coding bug but a data bug. 
Can I ask for you to email me the correlation matrix for your raw data? I could then simulate a dataset based upon that and then run the model. 

Please note that it would be best to *email* me the correlation matrix in order to protect your data. 

I hope this helps! 

Kind regards,
Nicholas Danks

**Comment by Mo-C1** [comment]
Dear Nicholas

Thank you for the fast and friendly reply. I provide you with the real, but
shortened and anonymized dataset to make things easier. The same error
occurs.
FYI: -77 is the value for "respondent entered no data".

Your help is much appreciated.

Best,
Moritz

Am Mo., 23. Nov. 2020 um 13:13 Uhr schrieb Nicholas Danks <
notifications@github.com>:

**Comment by NicholasDanks** [comment]
Dear Moritz

I would like to have a look and try to solve this issue you are encountering. Where did you say you had provided the data? Will you email it to me? 

Kind regards,
Nick

**Comment by Mo-C1** [comment]
Hi Nicholas,

I’ve sent it in my previous email, as you suggested.

Shall I send the file again?

Best
Moritz

**Comment by NicholasDanks** [comment]
Dear Moritz

Could you send it to me at nicholasdanks@hotmail.com?

Kind regards,
Nick

**Comment by NicholasDanks** [comment]
Dear Moritz

I hope you are well. Has this issue been resolved?
Please close the issue if it has.

Happy modeling!

**Comment by Mo-C1** [comment]
Hi Nicholas,

thank you so much for your help and sorry for my belated reply. 
I tried to run the code you suggested, but obtain an error when trying to run the clean_survey_data function:

`clean_survey_data <- seminr:::mean_replacement(surveyData[,c(multi_items("v_", 107:114),`
`+                                                              multi_items("v_", 115:121),`
`+                                                              c("v_38", "v_39", "v_40", "v_45"),`
`+                                                              c("v_41", "v_42", "v_43", "v_44", "v_46", "v_47"),`
`+                                                              c("v_49", "v_51", "v_54"),`
`+                                                              c("v_55", "v_56", "v_57"),`
`+                                                              c("v_61", "v_63", "v_64"),`
`+                                                              c("v_65", "v_66", "v_68", "v_69"),`
`+                                                              multi_items("v_", 144:151))])`
`Fehler in get(name, envir = asNamespace(pkg), inherits = FALSE) : `
`  Objekt 'mean_replacement' nicht gefunden`

... which means something along the lines of:
`Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : `
`  Did not find object 'mean_replacement' `

This is somewhat surprising, as the definition of mean_replament function at the top of your code seems to run through without causing problems. So does the loading of the CSV file.

Could this - again - be related to my data?

Thank you for your kind help and best wishes
Moritz

**Comment by NicholasDanks** [comment]
Dear Moritz

I apologize, I made a mistake in the code. Please try this:

mean_replacement <- function(data) {
  for (i in 1:ncol(data)) {
    colmean <- mean(data[,i][!(is.na(data[,i]))])
    data[,i][is.na(data[,i])] <- colmean
  }
  return(data)
}

surveyData <- read.csv2("data_project_832063_2020_11_23_mod3.csv")
missing_value = -77
surveyData[surveyData == missing_value] <- NA

clean_survey_data <- mean_replacement(surveyData[,c(multi_items("v_", 107:114),
                                                             multi_items("v_", 115:121),
                                                             c("v_38", "v_39", "v_40", "v_45"),
                                                             c("v_41", "v_42", "v_43", "v_44", "v_46", "v_47"),
                                                             c("v_49", "v_51", "v_54"),
                                                             c("v_55", "v_56", "v_57"),
                                                             c("v_61", "v_63", "v_64"),
                                                             c("v_65", "v_66", "v_68", "v_69"),
                                                             multi_items("v_", 144:151))])
measurements <- constructs(

  #Antecedents
  reflective("MOPRO", multi_items("v_", 107:114)),
  reflective("MORTN", multi_items("v_", 115:121)),

  composite("VDISC", c("v_38", "v_39", "v_40", "v_45"), weights = mode_B),
  composite("VCOC", c("v_41", "v_42", "v_43", "v_44", "v_46", "v_47"), weights = mode_B),
  composite("VQUAN", c("v_49", "v_51", "v_54"), weights = mode_B),
  composite("VBPRI", c("v_55", "v_56", "v_57"), weights = mode_B),
  composite("VCOMM", c("v_61", "v_63", "v_64"), weights = mode_B),
  composite("VLRNG", c("v_65", "v_66", "v_68", "v_69"), weights = mode_B),
  higher_composite("VBS", dimensions = c("VDISC","VCOC","VQUAN","VBPRI","VCOMM","VLRNG"), method = two_stage, weights = mode_B),
  reflective("SALSPERF", multi_items("v_", 144:151)) )

#Structural model definition

structure <- relationships(

  #paths (from = c("VDISC","VCOC","VQUAN","VBPRI","VCOMM","VLRNG"), to = "SALSPERF"),
  paths (from = c("MOPRO"), to = "VBS"),
  paths (from = c("MORTN"), to = "VBS"),
  paths (from = c("VBS"), to = "SALSPERF") )

print("End of structural model")

#Estimate model

pls_model <- estimate_pls ( data = clean_survey_data,
                            measurement_model = measurements,
                            structural_model = structure)
Kind regards,

Nicholas Patrick Danks
PhD.




On Dec 2, 2020, at 6:00 AM, Mo-C1 <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Nicholas,

thank you so much for your help and sorry for my belated reply.
I tried to run the code you suggested, but obtain an error when trying to run the clean_survey_data function:

clean_survey_data <- seminr:::mean_replacement(surveyData[,c(multi_items("v_", 107:114),
+ multi_items("v_", 115:121),
+ c("v_38", "v_39", "v_40", "v_45"),
+ c("v_41", "v_42", "v_43", "v_44", "v_46", "v_47"),
+ c("v_49", "v_51", "v_54"),
+ c("v_55", "v_56", "v_57"),
+ c("v_61", "v_63", "v_64"),
+ c("v_65", "v_66", "v_68", "v_69"),
+ multi_items("v_", 144:151))])
Fehler in get(name, envir = asNamespace(pkg), inherits = FALSE) :
Objekt 'mean_replacement' nicht gefunden

... which means something along the lines of:
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
Did not find object 'mean_replacement'

This is somewhat surprising, as the definition of mean_replament function at the top of your code seems to run through without causing problems. So does the loading of the CSV file.

Could this - again - be related to my data?

Thank you for your kind help and best wishes
Moritz
