### ISSUE TITLE
Errors with (README) examples

### ISSUE THREAD

**Issue by BenediktAllendorf** [sem-in-r/seminr#169]
I checked out the examples and found a few things I wanted to share! :)

### Missing bracket
```
structure <- relationships(
  paths(from = c("Image", "Expectation"), to = c("Complaints", "Loyalty")
)
```
should probably be (notice the additional closing bracket):
```
structure <- relationships(
  paths(from = c("Image", "Expectation"), to = c("Complaints", "Loyalty"))
)
```

Both in https://github.com/sem-in-r/seminr/blob/master/README.Rmd#L253 and https://github.com/sem-in-r/seminr/blob/master/README.Rmd#L58

### Non-existing variable name
`summary(mobi_pls)` should be `summary(pls_model)` in https://github.com/sem-in-r/seminr/blob/master/README.Rmd#L229

### Commas
https://github.com/sem-in-r/seminr/blob/master/README.Rmd#L128 should have a comma at the end of the line, https://github.com/sem-in-r/seminr/blob/master/README.Rmd#L130 should not.

I still get 
```Error in solve.default(iv_cors) : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0
```

in https://github.com/sem-in-r/seminr/blob/master/README.Rmd#L155 but I guess that's another problem.

**Comment by NicholasDanks** [comment]
Dear Benedikt

Thank you very much for taking the time to notify us about these bugs. I have now corrected them as per your suggestions and the code in the Readme should be running well.
Please reinstall the branch "Primer_preparation" by using:
```
devtools::install_github(repo = "https://github.com/sem-in-r/seminr.git", ref = "Primer_preparation")
```
If you can confirm that you also can execute these examples correctly, then please do close the issue.

Thanks again and happy modeling!
Kind regards,
Nick

**Comment by BenediktAllendorf** [comment]
Thanks for your fast reply! I checked it out and everything works smoothly now! 👍
