### ISSUE TITLE
Error with summary() function – second order composites

### ISSUE THREAD

**Issue by Arturocano997** [sem-in-r/seminr#176]
Hello!

The next error appears when trying to include summary(pls_model) into an object.

Warning message:
In stats::cor(seminr_model$data) : the standard deviation is zero

Does it mean there is an error with my model or is it a bug from the program?

thanks

**Comment by soumyaray** [comment]
Hi @Arturocano997 if you do a `cor(your_data)` outside of seminr, do you get an error?

**Comment by Arturocano997** [comment]
Thanks for your quick response Soumya.
I just tried the correlation function and no error appears!

**Comment by Arturocano997** [comment]
Wait a minute, it seems I missed something before. Indeed, the same error appears! So there must be a problem with the data I suppose, right?

**Comment by soumyaray** [comment]
yes! then its something wrong in the data — you can running cor() on groups of columns at a time to identify which one is causing the problems.

**Comment by soumyaray** [comment]
I'll close this issue for now but feel free to reopen it if you find something else that might be model or seminr related.
