### ISSUE TITLE
A very basic PLS-SEM model. 

### ISSUE THREAD

**Issue by JulianGaviriaL** [sem-in-r/seminr#227]
I post below a basic question on PLS-SEM modelling with seminr package. Thanks in advance for indicating me a more appropriated forum/site, in case this site is exclusive for reporting bugs. 

```
myDATA<-as.data.frame(myDATA)

# Define measurement model
measurements <- constructs(
 composite("X", multi_items("Brain_prev", 1:2), weights = mode_B),
 composite("Y", multi_items("Brain_curr", 1:2), weights = mode_B)
)
  
# structural model
structure <- relationships(
  paths(from = c("X"), to = c("Y"))
)

# Estimate the model using PLS estimation scheme (Consistent PLS for reflectives)
pls_model <- estimate_pls(data = myDATA, measurements, structure)

plot(pls_model, title = "PLS Model")
```
Question: According to the attached plot, the composite variable "Y" is not formative (see arrows). If this is true, how should I modify the script?

Thanks in advance, 
[data.xlsx](https://github.com/sem-in-r/seminr/files/6833446/data.xlsx)
  

![Rplot](https://user-images.githubusercontent.com/51994999/126009346-9e9acb2c-143e-4b57-aeb3-e01a3960dc42.png)

**Comment by Sumidu** [comment]
Hi Julian,
this does look like a bug. I will look into it tomorrow.
Thank you for reporting this here. It should be a quick fix.

**Comment by JulianGaviriaL** [comment]
Thanks André.

**Comment by NicholasDanks** [comment]
Thank you for pointing out this bug. We have implemented a bugfix (thank you Andre!). 
We will accumulate a few bugfixes and new features before releasing a new version. If you need to publish a model in the interim, you could install the bugfix version of SEMinR using the following code:
```remotes::install_github("https://github.com/sem-in-r/seminr.git", ref = "bugfix-227")```

Hope this helps and happy modeling.
Nick

**Comment by JulianGaviriaL** [comment]
It  worked fine. Thanks a lot @NicholasDanks  and Andre!

Best regards,
