### ISSUE TITLE
Computing prediction statistics (MAE, MAPE, RMSE values) in seminr

### ISSUE THREAD

**Issue by JulianGaviriaL** [sem-in-r/seminr#228]
Hello 
From the following model:

[data.xlsx](https://github.com/sem-in-r/seminr/files/6836761/data.xlsx)
```
# Define measurement model
measurements <- constructs(
 composite("X", multi_items("Brain_prev", 1:2), weights = mode_B),
 composite("Y", multi_items("Brain_curr", 1:2), weights = mode_B))
  
# structural model
structure <- relationships(
  paths(from = c("X"), to = c("Y")))

# Estimate the model using PLS estimation scheme (Consistent PLS for reflectives)
pls_model <- estimate_pls(data = myDATA, measurements, structure)

```
I computed "in-sample" and "out-sample" values with pls predict function:
```
#Prediction power:
cross_validated_predictions <- predict_pls(model = pls_model, technique = predict_DA, noFolds = NULL, reps = NULL, cores = NULL)
```
How can I compute MAE, MAPE, RMSE values? Thanks in advance for your comments.

**Comment by soumyaray** [comment]
Thanks for submitting the issue.  @NicholasDanks is best suited to answer these questions.  Kindly let him investigate and let us know.

**Comment by JulianGaviriaL** [comment]
Thanks Soumya for replying.

Have a nice day.

**Comment by NicholasDanks** [comment]
Oh and please do close this issue if you are satisfied. 

Regards,
Nick

**Comment by JulianGaviriaL** [comment]
the summary function nicely worked! Thank you very much. A couple of remaining  questions on this regard:

1) Is it possible to obtain Q2_predict values?
2) Following (Shmueli et al., 2019., Table1) I wonder how could I compare the distributions of the prediction errors from PLS-SEM with those from LM. Is it necessary to quantify their similarity? A visual inspection is enough? For this purpose, I tried to plotted them:
`plot(sum_cross_validated_predictions, indicator = "Brain_curr2")
`But I don't know how I could obtain the distributions of PLS-SEM and LM. 

3) the PLS predict results from the model above yielded the prediction errors for all endogenous _constructs’ indicators_:
```
> sum_cross_validated_predictions

PLS in-sample metrics:
     Brain_curr1 Brain_curr2
RMSE       5.543       4.178
MAE        4.434       3.390

PLS out-of-sample metrics:
     Brain_curr1 Brain_curr2
RMSE       6.241       4.635
MAE        4.947       3.793

LM in-sample metrics:
     Brain_curr1 Brain_curr2
RMSE       5.485       4.166
MAE        4.324       3.357

LM out-of-sample metrics:
     Brain_curr1 Brain_curr2
RMSE       6.296       4.628
MAE        4.980       3.774
```

 In accordance to Hair et al., 2019. P 13), how can I obtain the values from the endogenous _constructs_?

**Comment by NicholasDanks** [comment]
Dear Julian,

1. We do not include Q2 metrics in SEMinR. Refer to Shmueli et al. (2016) Appendix C for a discussion on the Q2 metric.
2. I cannot comment authoritatively on this question. I believe that it is only necessary to evaluate the PLS-SEM error for identifying the predictive metric which would be best. I believe you can conduct a statistical test to determine if the distribution is normal. However, I believe that a simple eye-ball test should suffice. 
3. We do not yet include the metrics for endogenous constructs. We have an article under review (and an update to our package) that will address this, but we have decided to only implement accepted and academically sound methods in SEMinR. So we await acceptance. 

I hope this helps. 

Please do remember to close old issues, and post new questions in new issues
Thank you kindly and happy modeling,
Nick

**Comment by JulianGaviriaL** [comment]
Thanks for your comments @NicholasDanks 

Best regards,
