### ISSUE TITLE
seminr vs plspm differences in resulting models

### ISSUE THREAD

**Issue by paullemmens** [sem-in-r/seminr#245]
As total beginner both in SEM / path modeling as well as with seminr, I'm running into the following. A colleague fitted a model using plspm with the following summary.

![image](https://user-images.githubusercontent.com/5063702/131090634-ab4f1ed7-a6c2-4814-9e12-0cbc52f83923.png)
![image](https://user-images.githubusercontent.com/5063702/131090661-b70e24c2-1201-4f25-9150-1e7981d9a65f.png)

I restructured the model into seminr language and found the model below.

```
meas <- constructs(
  composite('demographics', single_item(c('age', 'education'))),
  composite('general',      single_item(c('info_prefs_scientific', 'info_prefs_indepth',
                                          'info_prefs_actionable_recommendations'))),
  composite('personal',     single_item(c('info_prefs_feelings', 'info_prefs_personal_stories')))
)
struct <- relationships(
  paths(from = 'demographics', to = c('general', 'personal'))
)
```

![image](https://user-images.githubusercontent.com/5063702/131090526-27b42025-8803-44a7-bbd9-8e191443eb13.png)

The main differences that I'm seeing are the path of the outer model for age and education and the inner model (although to a somewhat lesser extent). The outer model paths for the info_prefs variables are (ballpark) similar to equivalent.

I'm curious to understand where these differences might come from. For one, plspm explicitly mentions parameters around scaling / standardization (also enabling specifying whether variables are ordinal, nominal, etc) which I haven't found in seminr's documentation. 

On the other hand, I haven't been able (due to lack of knowledge) to understand whether (simple) differences between the fitting procedure could account for the observed differences. I have verified that both fitting procedures have set mode A for weighting.

Would appreciate your suggestions or feedback!

**Comment by paullemmens** [comment]
Thanks @soumyaray and @NicholasDanks I'll need to anonymize the data to protect employer and will get back to you shortly.

Both sets of fitting code are as follows. For `seminr` in addition to the above specification, I'm fitting with 

```
mg_sem <- dat %>%
  select(age, education, starts_with('info_prefs_')) %>%
  estimate_pls(measurement_model = meas, structural_model = struct)
```

The `plspm` modeling:

```
tmp <- subset(survey,!is.na(survey$groom_freq_nose) & !is.na(survey$groom_freq_ears))
tmp <- subset(tmp,!is.na(tmp$appear_importance) & !is.na(tmp$appear_activity))
tmp <- subset(tmp,!is.na(tmp$info_prefs_scientific) & !is.na(tmp$info_prefs_indepth) & !is.na(tmp$info_prefs_actionable_recommendations))
tmp <- subset(tmp,!is.na(tmp$info_prefs_feelings) & !is.na(tmp$info_prefs_personal_stories))
demographics   = c(0,0,0)
info_t         = c(1,0,0)
info_p         = c(1,0,0)
mypath  = rbind(demographics,info_t,info_p)
colnames(mypath) = rownames(mypath)
myblocks = list(c(age, education),
                c(info_prefs_scientific,info_prefs_indepth,info_prefs_actionable_recommendations),
                c(info_prefs_feelings,info_prefs_personal_stories))
myscaling = list(c("ord","nom"),
                 c("ord","ord","ord"),
                 c("ord","ord"))
mymodes = c("A","A","A")
mypm = plspm(tmp, mypath, myblocks, modes = mymodes, scaling = myscaling)
```

There's one other difference that I just spotted which is the explict NA filtering in the `plspm` code. I think this is a leftover from earlier versions of the data that weren't as spit cleaned as they are now. Nevertheless, I'll double check and will let you know when I send the data.

**Comment by paullemmens** [comment]
Took me a little longer due to other priorities to recreate a minimized data set that reproduces the above problem. Just sent it, with accompanying script to your email @NicholasDanks @soumyaray. 

Thanks for looking into the difference(s)!

**Comment by NicholasDanks** [comment]
Dear Paul,

I hope you are well.
First, please accept my very sincere apologies for the delay in responding to you.
This is my first semester delivering 4 new modules of my own creation and i'm overwhelmed with syllabus development. 

I have done a little probing on the data and have settled on the nature of the difference in estimation. 
When I investigate the plspm() function RDocs, I note the following: 

```plspm(Data, path_matrix, blocks, modes = NULL,
    scaling = NULL, scheme = "centroid", scaled = TRUE,
    tol = 1e-06, maxiter = 100, plscomp = NULL,
    boot.val = FALSE, br = NULL, dataset = TRUE)
``` 

Thus plspm uses centroid as default while we use path weighting as default. This should account for a second or third decimal place difference - but not the large difference we see above.
On further investigation, I see that you have specified values for the ```scaling``` parameter.
specifically, you specify the following:
```
myscaling <- list(c("ord","nom"),
                 c("ord","ord","ord"),
                 c("ord","ord"))
```
 By specifying that some variables require alternate scaling based upon the nature of the variable:
```
scaling = 
optional argument for runing the non-metric approach; it is a list of string vectors indicating the type of measurement scale for each manifest variable specified in blocks. scaling must be specified when working with non-metric variables. Possible values: "num" (linear transformation, suitable for numerical variables), "raw" (no transformation), "nom" (non-monotonic transformation, suitable for nominal variables), and "ord" (monotonic transformation, suitable for ordinal variables).
```
You are scaling very differently than our algorithm does. Thus the consequent relationships are very different. 
We do not have such scaling options built into our software, and I do not have the necessary expertise in alternate transformations to comment on their suitability. Nonetheless, I have never seen such an application.

At least we now know the reason for the divergence in results, although I cannot advise you on the best method to be applied to your specific model. 

I hope this helps, and happy modeling.
Nick

**Comment by paullemmens** [comment]
Thank you @NicholasDanks for making time and effort for the elaborate analysis! Indeed the scaling parameter of `plspm` is/was one of the reasons why my colleague opted to use that package for model fitting. In the social sciences there is on the one hand a lot of pragmatism around handlingLikert-like rating scales but on the other hand it is just as much frowned upon when converting such ordina/nominal scales to interval/ratio scales.

So is it correct to presume that `seminr` simply takes non-metric scales and converts them to metric interval/ratio scales?
