### ISSUE TITLE
HOC plotting error with conflicting HOC name

### ISSUE THREAD

**Issue by NicholasDanks** [sem-in-r/seminr#259]
(from Facebook)
Dear group, may I ask for your help, with a problem I couldn't find an answer for elsewhere, unfortunately? 
I'll receive the following error when trying to plot a PLS model that includes higher-order composites:
"Error in get_construct_type(model, construct) : 
  object 'construct_type' not found"
Plots without HOCs work, as well as the HOC plot with the mobi dataset, however.
Thank you very much for your support in advance.
It's highly appreciated!
I just found the problem myself. The higher-order composites had the same names as the variables used in the multi items (e.g.
higher_composite("CO", dimensions = c("COs", "COc", "COo"), whereas the multi-items in the dimensions were called co1:co16). Changing the HOC name resolved the issue!

**Comment by soumyaray** [comment]
@NicholasDanks i don't see how the HOC's name "CO" conflicts with anything in the items?
