### ISSUE TITLE
Error in structural_model[, 1] : incorrect number of dimensions

### ISSUE THREAD

**Issue by HuqAsifM** [sem-in-r/seminr#264]
Hi! I'm trying to model the following and consistently getting the subject error. Many thanks in advance for your help. And thanks much to dear Soumya for many helpful suggestions already. I am attaching a subset of the data I'm working with.

measurements2 <- constructs(
  reflective("ProValue", multi_items("Age_years", "children", "work")),
  reflective("ValExp", multi_items("ChooseService", "TotShoppast", "ChooseProductOffer")), 
  reflective("PerRisk", multi_items("household", "accomendation", "StartConvenience")),
  higher_reflective("PerValue", c("ProValue", "ValExp", "PerRisk")),
  composite("PurIntConstruct", single_item("PurInt"), 
            weights = regression_weights),
  reflective("PerValue", single_item("PurIntConstruct")
  )
  )

structural2 <- relationships(
  paths(from = "PerValue", to = "PurIntConstruct")
)

model_est <- estimate_pls(survey, structural2, measurements2,
                          inner_weights = path_weighting,
                          maxIt=300, stopCriterion=7) #

[survey_pls_02032022.xlsx](https://github.com/sem-in-r/seminr/files/7996972/survey_pls_02032022.xlsx)

**Comment by soumyaray** [comment]
@HuqAsifM I've got a working version. I had to make several changes to your syntax. Please see the code below and notes in it.

```r

library(readxl)
library(seminr)

survey <- read_xlsx("survey_pls_02032022.xlsx")

# Changes:
# - multi_items(0) is only for items with same prefixes - use c() for arbitrary collection of items
# - "ChooseService" item not in data - using "StartService" instead
# - higher_reflective() is not yet supported for PLS, only for CBSEM; using higher_composite() instead
measurements2 <- constructs(
  reflective("ProValue", c("Age_years", "children", "work")),
  reflective("ValExp", c("StartService", "TotShoppast", "ChooseProductOffer")),
  reflective("PerRisk", c("household", "accomendation", "StartConvenience")),
  higher_composite("PerValue", c("ProValue", "ValExp", "PerRisk"), weights = mode_A),
  composite("PurIntConstruct", single_item("PurInt"))
)

structural2 <- relationships(
  paths(from = "ProValue", to = "PurIntConstruct")
)

model_est <- estimate_pls(survey, measurements2, structural2, 
                          inner_weights = path_weighting,
                          maxIt=300, stopCriterion=7)

model_est$path_coef
```

**Comment by soumyaray** [comment]
@HuqAsifM I'll close this issue for now -- feel free to reopen it if you continue facing difficulties.

**Comment by HuqAsifM** [comment]
Dear @soumyaray, Thank you so much for all the help! I'll work with it soon.
