### ISSUE TITLE
Error in solve.default(construct_score_cors[c(independant, dependant[i])

### ISSUE THREAD

**Issue by koliajaykr** [sem-in-r/seminr#265]
upon running the `estimate_pls()` the execution is halted with this error:

`Error in solve.default(construct_score_cors[c(independant, dependant[i]),  : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0
Calls: <Anonymous> ... <Anonymous> -> calc_insample -> solve -> solve.default
Execution halted`

Kindly guide me on what could be the source of this error. Thank you in anticipation.

**Comment by soumyaray** [comment]
Dear @koliajaykr this issue usually arises when two or more of your constructs have nearly identical (highly collinear) scores.  Perhaps you can try to see if there are items that are nearly identical across constructs using a simple correlation matrix. Or else, please provide us a sample of the code and data that is producing this error. You may email it to me privately (see my Github profile) if you wish or post it here.

**Comment by koliajaykr** [comment]
Somehow this issue is resolved by reducing the number of `paths` inside the `relationships()` function. But still, I am interested to know what roughly this error means. Thank you.

**Comment by soumyaray** [comment]
> Somehow this issue is resolved by reducing the number of `paths` inside the `relationships()` function. But still, I am interested to know what roughly this error means. Thank you.

sure -- please see my reply above.  there is a relationship where constructs involved are likely nearly identical.

**Comment by koliajaykr** [comment]
> 

you are absolutely correct about the addition of similar paths. thank you so much for your prompt reply. it is so kind of you. :)
