### ISSUE TITLE
Error while trying to plot PLS-SEM model

### ISSUE THREAD

**Issue by sandeepdey98** [sem-in-r/seminr#266]
Hello @soumyaray sir jee,

here is the new issue I have opened. the following is my code with the error being returned.
```
library(seminr)
attach(GreenPB)
survey.data<- GreenPB
```
```
measurement<- constructs(
  composite("ATT", multi_items("ATT", 1:5)),
  composite("INT", multi_items("INT", 1:3)),
  composite("PAE", multi_items("PAE", 1:4)),
  composite("NAE", multi_items("NAE", 1:4)),
  composite("SUB", multi_items("SUB", 1:3)),
  composite("PBC", multi_items("PBC", 1:3)),
  composite("DES", multi_items("DES", 1:3)),
  composite("GRE", multi_items("GRE", 1:5)),
  composite("DGB", multi_items("DGB", 1:3)),
  composite("MDF", multi_items("MDF", 1:4)), 
  composite("GPB", multi_items("GPB", 1:4)),
  interaction_term(iv="INT", moderator = "GRE", method = product_indicator),
  interaction_term(iv="INT", moderator = "MDF", method = product_indicator)
)
```
```
structure<- relationships(
  paths(from = "ATT", to="DES"),
paths(from = "PAE", to="DES"),
paths(from = "NAE", to="DES"),
paths(from = "SUB", to="DES"),
paths(from = "PBC", to="DES"),
paths(from = "DES", to="INT"),
paths(from=  "INT", to="GPB"),
paths(from = "DGB", to = "GPB"),
paths(from = "PBC", to="GPB"),
paths(from = "INT*GRE", to= "GPB"),
paths(from = "INT*MDF", to="GPB")
)
```
```
greenpb_pls <- estimate_pls(
  data = survey.data,
  measurement_model = measurement,
  structural_model = structure,
  inner_weights = path_weighting
)
```
```
greenpb_cfa <- estimate_cfa(
  data = survey.data,
  measurement_model = as.reflective(measurement)
)
```
```
boot_estimates <- bootstrap_model(greenpb_pls, nboot = 100, cores = 1)
```
plot(boot_estimates, title = "Bootstrapped Model")
```
```
Error in model$outer_loadings[indicator, construct] : 
  subscript out of bounds
```

**Comment by soumyaray** [comment]
Thanks for the much improved code presentation @sandeepdey98 -- Can I ask if the error is only happening on the plot command?

**Comment by soumyaray** [comment]
and unrelated, the structural model can be written more simply as:
```
structure<- relationships(
  paths(from = c("ATT", "PAE", "NAE", "SUB", "PBC"), to="DES"),
  paths(from = "DES", to="INT"),
  paths(from =  c("INT", "DGB", "PBC", "INT*GRE", "INT*MDF"), to="GPB")
)
```

**Comment by soumyaray** [comment]
@sandeepdey98 could you kindly try the following to see if they work?

1. Only define constructs in the measurement model that will be used in the structural model

2. If the above doesn't help, ALSO start by removing all items in your dataset (`survey.data`) that are not used in the model? 

We have noted similar bugs before and I think it will be an easy fix if one of the above solves your issue

**Comment by sandeepdey98** [comment]
> Thanks for the much improved code presentation @sandeepdey98 -- Can I ask if the error is only happening on the plot command? Everything else works?

Everything else works , only the plot command.

**Comment by soumyaray** [comment]
@sandeepdey98 please try to add GRE and MDF as antecedents of GPB (main variables should always be included as antecedents when creating an interaction out of them). Let me know if that resolves it.

**Comment by soumyaray** [comment]
Glad it worked!! We will also internally consider whether using an interaction term without main effects, even if invalid, should still be plotted (perhaps with a warning notice). Thanks for bringing this to our attention.
