### ISSUE TITLE
Which R package to use with SEMinR to print tables in the pdf output?

### ISSUE THREAD

**Issue by koliajaykr** [sem-in-r/seminr#268]
For producing tables there are several R packages like kableExtra, gt, and stargazer. Which R package do you recommend for pdf and word output?

**Comment by soumyaray** [comment]
Dear @koliajaykr that's a terrific question and I regret that I don't have a great answer for you. `Stargazer` has been a perennial favorite for R users, though `kableextra` and `gt` are gaining popularity.  One consideration might be which output formats each package supports. `gt`, for example, used to mainly support HTML output though now it seems to support RTF and LaTex. You will want to consider which software you are producing your final report in to see how well each package integrates with it.

Please share with us here if you come to any conclusions yourself. It would be a great contribution to our further development. I'll keep this issue open for now in case we wish to integrate SEMinR with an output package in future. On that note, do also let us know if you think its better we remain agnostic to output packages and offer other ways of integrating with them.

**Comment by koliajaykr** [comment]
@soumyaray thank you for your reply.

I tried to use the R package `kableExtra` for generating HTML output and it is working good.
