### ISSUE TITLE
Wanting to check if I have coded in my moderators correctly 

### ISSUE THREAD

**Issue by Finnug** [sem-in-r/seminr#272]
[Blank diagram.pdf](https://github.com/sem-in-r/seminr/files/8370209/Blank.diagram.pdf)

Hello, 

I'm currently creating a PLS-SEM model for my university dissertation applied to the Universal Theory of Technology And Acceptance and applying it to the intention to use Bitcoin. I have finished my code however once I added in the moderators of gender, age and experience (UsedBTC), the R squared value didn't change. I wanted to check whether I had coded in the moderators to the model correctly or if I'm missing something. Please see diagram attached to see where the paths go in terms of the model and the moderators. Any help/advice would be greatly appreciated. Here is the code:

# Create measurement model
simple_mm <- constructs(
  composite("performanceexpectancy", multi_items("PE", 1:3)),
  composite("effortexpectancy", multi_items("EE", 1:4)),
  composite("socialinfluence", multi_items("SI" , 1:3)), 
  composite("facilitatingconditions", multi_items("FC", 1:3)),
  composite("behaviouralintention", multi_items("BI", 1:4)),
  composite("perceivedrisk", multi_items("PR", 1:3)),
  composite("financialliteracy", multi_items("FL", 1:2)),
  composite("usedbitcoin", single_item("USEDBTC")),
  composite("gender", single_item("Gender")),
  composite("age", single_item("AGE")),
  interaction_term(iv = "effortexpectancy", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "facilitatingconditions", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "socialinfluence", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "perceivedrisk", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "financialliteracy", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "effortexpectancy", moderator = "gender", method = two_stage),
  interaction_term(iv = "socialinfluence", moderator = "gender", method = two_stage),
  interaction_term(iv = "perceivedrisk", moderator = "gender", method = two_stage),
  interaction_term(iv = "performanceexpectancy", moderator = "gender", method = two_stage),
  interaction_term(iv = "performanceexpectancy", moderator = "age", method = two_stage),
  interaction_term(iv = "effortexpectancy", moderator = "age", method = two_stage),
  interaction_term(iv = "facilitatingconditions", moderator = "age", method = two_stage),
  interaction_term(iv = "socialinfluence", moderator = "age", method = two_stage),
  interaction_term(iv = "perceivedrisk", moderator = "age", method = two_stage))

# Create structural model

simple_sm <- relationships(paths(from = c("performanceexpectancy", "effortexpectancy", "socialinfluence", "facilitatingconditions", "perceivedrisk", "financialliteracy"), to = c("behaviouralintention")),
                                        paths(from = c("usedbitcoin"), to = c("effortexpectancy")),
                                        paths(from = c("usedbitcoin"), to = c("facilitatingconditions")),
                                        paths(from = c("usedbitcoin"), to = c("socialinfluence")),
                                        paths(from = c("usedbitcoin"), to = c("perceivedrisk")),
                                        paths(from = c("usedbitcoin"), to = c("financialliteracy")),
                                        paths(from = c("gender"), to = c("effortexpectancy")),
                                        paths(from = c("gender"), to = c("performanceexpectancy")),
                                        paths(from = c("gender"), to = c("socialinfluence")),
                                        paths(from = c("gender"), to = c("perceivedrisk")),
                                        paths(from = c("age"), to = c("effortexpectancy")),
                                        paths(from = c("age"), to = c("facilitatingconditions")),
                                        paths(from = c("age"), to = c("socialinfluence")),
                                        paths(from = c("age"), to = c("perceivedrisk")),
                                        paths(from = c("age"), to = c("performanceexpectancy")))
  
There are no errors that come out of it however I think I feel like i'm missing something in the second 'create structural model' section. 

Thanks :)

Fin

**Comment by soumyaray** [comment]
Hi Fin, it seems you have not put your interaction terms into the structural model yet!

See this demo that comes with SEMinR: https://github.com/sem-in-r/seminr/blob/master/demo/seminr-pls-interaction.R

For example, in the measurement model we specify an interaction term as:
```
mobi_mm <- constructs(
  # omitting regular constructs
  interaction_term(iv = "Image", moderator = c("Expectation"), method = product_indicator, weights = mode_A),
  interaction_term(iv = "Image", moderator = c("Value"), method = product_indicator, weights = mode_A)
)
```

And in the structural model we include the interaction using `Image*Expectation` and `Image*Value`:
```
paths(from = c("Image", "Expectation", "Value", "Image*Expectation", "Image*Value"), to = "Satisfaction")
```

You should be able to see the interaction terms as constructs in the graphical view of the model (`plot(your_estimated_model)`).

**Comment by Finnug** [comment]
Ok thank you! If you wouldn't mind looking at my diagram please would the correct way to write this interaction be:

paths(from = c("usedbitcoin", "usedbitcoin*effortexpectancy"), to = c("effortexpectancy")) - for the first line in the structural code. If this is correct I would repeat it for all each path stated in the code.

Thanks for the reply :)

**Comment by Finnug** [comment]
@soumyaray pls see above :)

**Comment by soumyaray** [comment]
@Finnug, several things:

1. I believe the image you showed is wrong? shouldn't arrows go from antecedents like `effortexpectancy` to the outcome `behaviouralintention`? I'll continue with this assumption.
2. I think you will have to specify the constructs in the name of the interaction term in the order of iv*moderator. So: `effortexpectancy*usedbitcoin`. Try it both ways.
3. The outcome should be `behaviouralintention` so that should be the `to` end of the path; you can delete all the paths from moderators to antecedents.
4. Moderators in SEM/regression should also be IVs to the outcome (`behaviouralintention`)

Putting the above together, I believe the way to add a single interaction (`effortexpectancy*usedbitcoin`) to the structural model would be:

```
simple_sm <- relationships(
  paths(
    from = c("performanceexpectancy", "effortexpectancy", "socialinfluence", "facilitatingconditions", "perceivedrisk", "financialliteracy"), to = "behaviouralintention"),
    paths(from=c("usedbitcoin", "effortexpectancy*usedbitcoin"), to="behaviouralintention")
)
```

I added the moderator and interaction path to outcome as a new path command, just for clarity.

Also, as your model is getting increasingly complex (!!) I would suggest adding interactions to the structural model one at a time and running it with an added interaction each time.

**Comment by Finnug** [comment]
@soumyaray Thanks for all the help! Firstly, yes the arrows are wrong they're meant to go to behavioural intention. 

To clarify a couple of things - as far as I understand my measurement model is constructed fine, but the structural is the issue. I have just attempted to run the code that you suggested and have received this error message:

`> simple_sm <- relationships(paths(from = c("performanceexpectancy", "effortexpectancy", "socialinfluence", "facilitatingconditions", "perceivedrisk", "financialliteracy"), to = c("behaviouralintention")),
+                                         paths(from = c("usedbitcoin", "effortexpectancy*usedbitcoin"), to = c("behaviouralintention")))
> # Estimate the model
> Bitcoin.model <- estimate_pls(data = nomissing,
+                               measurement_model = simple_mm,
+                               structural_model = simple_sm)
Generating the seminr model
Error in first_stage$construct_scores[, moderator] : 
  subscript out of bounds`

I had this error yesterday and it sorted itself out with typing errors but I can't see any. 

Thanks again for all your help with this as I would be very stuck without.

**Comment by Finnug** [comment]
@soumyaray not sure what happened there sorry, first time using github. 

full code:

> simple_sm <- relationships(paths(from = c("performanceexpectancy", "effortexpectancy", "socialinfluence", "facilitatingconditions", "perceivedrisk", "financialliteracy"), to = c("behaviouralintention")),
+                                         paths(from = c("usedbitcoin", "usedbitcoin*effortexpectancy"), to = c("behaviouralintention")))
> # Estimate the model
> Bitcoin.model <- estimate_pls(data = nomissing,
+                               measurement_model = simple_mm,
+                               structural_model = simple_sm)
Generating the seminr model
Error in first_stage$construct_scores[, moderator] : 
  subscript out of bounds

**Comment by Finnug** [comment]
@soumyaray > 

'simple_sm <- relationships(paths(from = c("performanceexpectancy", "effortexpectancy", "socialinfluence", "facilitatingconditions", "perceivedrisk", "financialliteracy"), to = c("behaviouralintention")),
+                                         paths(from = c("usedbitcoin", "usedbitcoin*effortexpectancy"), to = c("behaviouralintention")))
> # Estimate the model
> Bitcoin.model <- estimate_pls(data = nomissing,
+                               measurement_model = simple_mm,
+                               structural_model = simple_sm)
Generating the seminr model
Error in first_stage$construct_scores[, moderator] : 
  subscript out of bounds'

**Comment by Finnug** [comment]
`> simple_sm <- relationships(paths(from = c("performanceexpectancy", "effortexpectancy", "socialinfluence", "facilitatingconditions", "perceivedrisk", "financialliteracy"), to = c("behaviouralintention")),
+                                         paths(from = c("usedbitcoin", "usedbitcoin*effortexpectancy"), to = c("behaviouralintention")))
> # Estimate the model
> Bitcoin.model <- estimate_pls(data = nomissing,
+                               measurement_model = simple_mm,
+                               structural_model = simple_sm)
Generating the seminr model
Error in first_stage$construct_scores[, moderator] : 
  subscript out of bounds`

**Comment by Finnug** [comment]
@soumyaray sorry not sure what happened there. Here is the full code

 simple_sm <- relationships(paths(from = c("performanceexpectancy", "effortexpectancy", "socialinfluence", "facilitatingconditions", "perceivedrisk", "financialliteracy"), to = c("behaviouralintention")),
                                        paths(from = c("usedbitcoin", "usedbitcoin*effortexpectancy"), to = c("behaviouralintention")))


 Bitcoin.model <- estimate_pls(data = nomissing,
                              measurement_model = simple_mm,
                             structural_model = simple_sm)

Generating the seminr model
Error in first_stage$construct_scores[, moderator] : 
  subscript out of bounds

**Comment by soumyaray** [comment]
@Finnug would it be possible to provide me a sample of your data and the full code?  I can try running it on my end to diagnose.  Your data and code will be kept confidentially and deleted when we resolve the issue. You may find my email on my [Github profile](https://github.com/soumyaray).

**Comment by Finnug** [comment]
@soumyaray Have emailed :)

**Comment by soumyaray** [comment]
Ok it was a problem in model specification. Here's the working code for your entire model (I think):

```
# Estimate the model
simple_mm <- constructs(
  composite("performanceexpectancy", multi_items("PE", 1:3)),
  composite("effortexpectancy", multi_items("EE", 1:4)),
  composite("socialinfluence", multi_items("SI" , 1:3)),
  composite("facilitatingconditions", multi_items("FC", 1:3)),
  composite("behaviouralintention", multi_items("BI", 1:4)),
  composite("perceivedrisk", multi_items("PR", 1:3)),
  composite("financialliteracy", multi_items("FL", 1:2)),
  composite("usedbitcoin", single_item("USEDBTC")),
  composite("gender", single_item("Gender")),
  composite("age", single_item("AGE")),
  interaction_term(iv = "effortexpectancy", moderator = "usedbitcoin", method = product_indicator),
  interaction_term(iv = "facilitatingconditions", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "socialinfluence", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "perceivedrisk", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "financialliteracy", moderator = "usedbitcoin", method = two_stage),
  interaction_term(iv = "effortexpectancy", moderator = "gender", method = two_stage),
  interaction_term(iv = "socialinfluence", moderator = "gender", method = two_stage),
  interaction_term(iv = "perceivedrisk", moderator = "gender", method = two_stage),
  interaction_term(iv = "performanceexpectancy", moderator = "gender", method = two_stage),
  interaction_term(iv = "performanceexpectancy", moderator = "age", method = two_stage),
  interaction_term(iv = "effortexpectancy", moderator = "age", method = two_stage),
  interaction_term(iv = "facilitatingconditions", moderator = "age", method = two_stage),
  interaction_term(iv = "socialinfluence", moderator = "age", method = two_stage),
  interaction_term(iv = "perceivedrisk", moderator = "age", method = two_stage)
)

# Structural model

simple_sm <- relationships(
  paths(from = c("performanceexpectancy", "effortexpectancy", "socialinfluence", "facilitatingconditions", "perceivedrisk", "financialliteracy"), to = c("behaviouralintention")),
  paths(from = c("usedbitcoin", "effortexpectancy*usedbitcoin", "facilitatingconditions*usedbitcoin", "socialinfluence*usedbitcoin", "perceivedrisk*usedbitcoin", "financialliteracy*usedbitcoin"), to = c("behaviouralintention")),
  paths(from = c("gender", "effortexpectancy*gender", "socialinfluence*gender", "perceivedrisk*gender", "performanceexpectancy*gender"), to = c("behaviouralintention")),
  paths(from = c("age", "performanceexpectancy*age", "effortexpectancy*age", "facilitatingconditions*age", "socialinfluence*age", "perceivedrisk*age"), to = c("behaviouralintention"))
)


Bitcoin.model <- estimate_pls(data = nomissing,
                              measurement_model = simple_mm,
                              structural_model = simple_sm)
```

Note that I am including each moderator (e.g., `gender`) and its interaction terms (e.g., `effortexpectancy*gender`) as IVs that explain the outcome.

Do let us know if this resolves the problem.

**Comment by Finnug** [comment]
I’ve just ran all the code and it works! My R Squared has gone up to 76 instead of 69 now which means my model is better than the one I’m developing on by 6 percentage points! 

Thanks so much you’re a life saver Soumya :) 

Best,

Fin

**Comment by soumyaray** [comment]
Best of luck on your research!

**Comment by Finnug** [comment]
Hi Soumya,

This is a big ask and feel free to say no but you’ve been really helpful so I thought that I may as well ask. Now the model is done, I’m struggling to see how I could write hypotheses for these results. I initially planned to not have moderators for them so my 6 hypotheses were these: 

Performance Expectancy positively influences the intention to use Bitcoin as a currency.

 

Effort expectancy positively influences the intention to use Bitcoin as a currency.

 

Social influence positively influences the intention to use Bitcoin as a currency.

 

Facilitating conditions positively influences the intention to use Bitcoin as a currency.

 

Perceived risk negatively influences the intention to use Bitcoin as a currency.

 

Financial literacy positively influences the intention to use Bitcoin as a currency.



I can see that 4/6 are supported by the p-values as shown below:

                                                                   paths    tvalues pvalues
performanceexpectancy  ->  behaviouralintention               0.36005188  2.8061467   0.003
effortexpectancy  ->  behaviouralintention                   -0.13982514 -1.0946966   0.863
socialinfluence  ->  behaviouralintention                     0.16599501  1.5184645   0.065
facilitatingconditions  ->  behaviouralintention              0.29592835  2.8605818   0.002
perceivedrisk  ->  behaviouralintention                       0.19792301  1.9686150   0.025
financialliteracy  ->  behaviouralintention                   0.04260612  0.5862921   0.279
usedbitcoin  ->  behaviouralintention                        -0.14559487 -1.3311616   0.908
effortexpectancy*usedbitcoin  ->  behaviouralintention       -0.05354560 -0.3244277   0.627
facilitatingconditions*usedbitcoin  ->  behaviouralintention -0.07554654 -0.6013224   0.726
socialinfluence*usedbitcoin  ->  behaviouralintention        -0.14466881 -1.4164038   0.921
perceivedrisk*usedbitcoin  ->  behaviouralintention           0.13087137  1.3987470   0.082
financialliteracy*usedbitcoin  ->  behaviouralintention       0.12529582  1.4717826   0.071
gender  ->  behaviouralintention                             -0.02700987 -0.4770847   0.683
effortexpectancy*gender  ->  behaviouralintention             0.02003503  0.2812846   0.389
socialinfluence*gender  ->  behaviouralintention              0.06608110  0.6579596   0.256
perceivedrisk*gender  ->  behaviouralintention               -0.05568850 -0.6766302   0.750
performanceexpectancy*gender  ->  behaviouralintention       -0.02277063 -0.2094181   0.583
age  ->  behaviouralintention                                -0.11750862 -1.8102585   0.964
performanceexpectancy*age  ->  behaviouralintention           0.04330977  0.3209933   0.374
effortexpectancy*age  ->  behaviouralintention               -0.05306406 -0.4846997   0.686
facilitatingconditions*age  ->  behaviouralintention          0.08244031  0.7170473   0.237
socialinfluence*age  ->  behaviouralintention                -0.03294590 -0.2703763   0.606
perceivedrisk*age  ->  behaviouralintention                  -0.01634825 -0.1867876   0.574

For my paper do I need a hypotheses for each path created here? 

I wanted to state my hypotheses as something like ’the influence of effort expectancy on BI will be moderated by experience, age and gender such that the effect will be stronger for people who haven’t used BTC, are older and are female’ - however, as there are 3 p-values for each moderated variable I’m not sure how to know whether this is supported. Would I need 3 individual hypotheses instead of combining? 

Any help is much appreciated. 

Thanks in advance,

Fin

**Comment by soumyaray** [comment]
Hi @Finnug, you should have one hypothesis for each interaction: e.g., "the influence of effort expectancy on BI will be [negatively/positively] moderated by experience". You must have one test statistic to validate each hypothesis.
