### ISSUE TITLE
Composite scores for latent variables: only two variables out of 4 were given

### ISSUE THREAD

**Issue by DrMedfaresBrini** [sem-in-r/seminr#273]
Dear all,
I have 4 latent variables in my model (two of them are higher-order constructs). I asked for the composite scores for each but only got the scores for two. 
This is part of my code:
# Create measurement model
mm <- constructs(
  composite("values", multi_items("MV", 1:3)),
  composite("endurance", multi_items("ET",1:3)),
  composite("compliance", multi_items("COMP", 1:3)),
  higher_composite("PMC", c("values","endurance","compliance"), method = two_stage),
  
  composite("transcend", multi_items("ST", 1:5)),
  composite("emotional1", c ("EI2","EI1")),
  composite("emotional2", c("EI4","EI3")),
  composite("emotional3", c("EI6","EI5")),
  composite("emotional4", c("EI8","EI7")),
  composite("emotional5", c("EI10","EI9")),
  higher_composite("emotional_intelligence", 
                   c("emotional1","emotional2","emotional3","emotional4", "emotional5"), method = two_stage),
  
  composite("corporate", multi_items("CEV", 3:5)))
plot(mm)
# Create structural model
sm <- relationships(
  paths(from = c("transcend", "emotional_intelligence"), to = "PMC"), 
  paths(from = "PMC", to = "corporate"))
# Estimate the model
final_model <- estimate_pls(data = database,
                             measurement_model = mm,
                             structural_model = sm)
# Summarize the model results
summary_simple <- summary(final_model)
plot(final_model)
#To Display all the contents in the summary_simple Object
summary_simple$reliability
summary_simple$loadings
summary_simple$validity$htmt
summary_simple$validity$cross_loadings
summary_simple$composite_scores

This is the output for the composite scores:
summary_simple$composite_scores
     transcend  corporate
1  -0.76707479  0.6213872
2   0.80496538 -1.6655295
3  -0.51181743  0.4229238
4  -0.50442268  0.1673261
5  -0.93944119  0.9206115

What could be the issue?

Thank you

**Comment by NicholasDanks** [comment]
Dear @DrMedfaresBrini 
thanks for your interest in the package. The first-order construct scores are stored in the estimated model object. Thus: 
```
final_model$first_stage_model$construct_scores   
```

Please do let me know if this helps.
Kind regards,
Nick

**Comment by DrMedfaresBrini** [comment]
Hi @NicholasDanks 
Thank you for the reply. 
- Yes, I had the scores for all the lower-order constructs (emotional {1...5}; values-endurance-compliance)
- plus, the two latent variables (transcend, corporate) (they're not HOC)
- but, not for the two HOC emotional_intelligence and PMC (please see the picture of my model attached to figure these variables)

I think the HOC scores should be calculated since these are basically the elements of the structural model 

Thank you very much
![final model](https://user-images.githubusercontent.com/99718351/160839209-e40032c3-b789-4b6f-9dcf-816460f871d2.jpg)

**Comment by NicholasDanks** [comment]
Dear @DrMedfaresBrini 
Thank you for pointing out this interesting edge-case. It seems the summary() function is editing out the constructs. 
For now, you can access the construct scores directly in the model and not in the summarized model. 
That is you should find the constructs scores for corporate, PMC, emotional_intelligence, and transcend in:
```
final_model$construct_scores"
```
And you should find the remaining construct scores of emotional1 - emotional5, and values, endurance, and compliance at :
```
final_model$first_stage_model$construct_scores  
```

In the meantime, we will on correcting this bug and updating SEMinR.
Thank you again for sharing your bug and helping us to improve SEMinR. 

Kind regards,
Nick

**Comment by DrMedfaresBrini** [comment]
Hi @NicholasDanks 
Thank you very much. It is all good now.
