### ISSUE TITLE
Error in plotting the bootstrapped model with SEMinR

### ISSUE THREAD

**Issue by alibezzaa** [sem-in-r/seminr#288]
I'm trying to plot a PLS-SEM model with SEMinR and I get the following error : 
Error in model$outer_loadings[indicator, construct] : 
  subscript out of bounds
I have never come across this error before.

[script.pdf](https://github.com/sem-in-r/seminr/files/8708444/script.pdf)

**Comment by soumyaray** [comment]
Greetings @alibezzaa may I inquire if the issue is resolved?

**Comment by alibezzaa** [comment]
Yes, thank you it was only a code mistake in the interaction term.

I have another question on second-order constructs, can I ask just here or should I go through Github?
________________________________
De : Soumya Ray ***@***.***>
Envoyé : jeudi 19 mai 2022 13:52
À : sem-in-r/seminr ***@***.***>
Cc : Ali BEZZAA ***@***.***>; Mention ***@***.***>
Objet : Re: [sem-in-r/seminr] Error in plotting the bootstrapped model with SEMinR (Issue #288)


Greetings @alibezzaa<https://github.com/alibezzaa> may I inquire if the issue is resolved?

**Comment by alibezzaa** [comment]
I will share with you the model I'm working on (N=71). I have two constructs that are theoretically second-order and have been measured as so, well-being at work and technostress. Well-being has two underlying dimensions and technostress four (only two shown) because I'm still collecting data to improve fit.
I have two issues to resolve:

  *   Is it appropriate to plot the model the way I did? Or use a first-order construct instead?
  *   How do I get rid of the indicators' loadings from the plot() and keep only the structural model for publication purposes?

________________________________
De : Soumya Ray ***@***.***>
Envoyé : jeudi 19 mai 2022 14:23
À : sem-in-r/seminr ***@***.***>
Cc : Ali BEZZAA ***@***.***>; Mention ***@***.***>
Objet : Re: [sem-in-r/seminr] Error in plotting the bootstrapped model with SEMinR (Issue #288)


Yes you can certainly ask it here and we can see if it warrants a separate issue.
