### ISSUE TITLE
using internal lavaan slots

### ISSUE THREAD

**Issue by yrosseel** [sem-in-r/seminr#293]
I noticed that seminr sometimes uses lavaan internal `@ `slots, which is discouraged (as they often change). In `report_lavaan.R`, we have `lavaan_output@Model@estimator`, `lavaan_output@call`, and `lavaan_output@Options$estimator`. They should be replaced by `lavInspect(lavaan_output, "options")$estimator` and `lavInspect(lavaan_output, "call")`.  In `estimate_factor_scores.R`, we have
`fit@SampleStats@mean[[1]]` and `fit@SampleStats@var[[1]]` which could be replace by `lavInspect(fit, "sampstat")$mean` and
`diag(lavInspect(fit, "sampstat")$cov)`(although the former will only be available if the model was fit with `meanstructure = TRUE`.

**Comment by NicholasDanks** [comment]
Thanks Yves, we have updated the code and pushed to CRAN

**Comment by yrosseel** [comment]
Much appreciated! Thanks!

Yves.
