### ISSUE TITLE
Error in generating the seminr model for CFA 

### ISSUE THREAD

**Issue by SatishAmbhore** [sem-in-r/seminr#304]
![1660823724007blob](https://user-images.githubusercontent.com/111578134/185624132-ddfa6e60-b073-4e55-8e8e-73166f4bd452.jpg)

Dear sir,
Greetings!

Kindly peruse the above screenshot. I am consistently receiving these errors. Kindly advice the solution please.

Warm regards,
Satish Ambhore

PhD (Psychology), NET, SET, DSE(HI)
Scientific Officer (Psychology)  
Central Railway Headquarter,
Office of Chief Safety Officer,
Chhatrapati Shivaji Maharaj Terminus,
Mumbai-400 001.

**Comment by NicholasDanks** [comment]
See the response on Github issues:
https://github.com/sem-in-r/seminr/issues/304


On 19 Aug 2022, at 14:04, SatishAmbhore ***@***.******@***.***>> wrote:



[1660823724007blob]<https://user-images.githubusercontent.com/111578134/185624132-ddfa6e60-b073-4e55-8e8e-73166f4bd452.jpg>

Dear sir,
Greetings!

Kindly peruse the above screenshot. I am consistently receiving these errors. Kindly advice the solution please.

Warm regards,
Satish Ambhore

PhD (Psychology), NET, SET, DSE(HI)
Scientific Officer (Psychology)
Central Railway Headquarter,
Office of Chief Safety Officer,
Chhatrapati Shivaji Maharaj Terminus,
Mumbai-400 001.

**Comment by SatishAmbhore** [comment]
Thanks a lot sir.
