### ISSUE TITLE
 predictive power assessment in SEMinR

### ISSUE THREAD

**Issue by isagul233** [sem-in-r/seminr#312]
Hello everyone.
I m testing a model like below. I will evaluate the predictive power of my model. 
--Should I evaluate out-of-sample LM-RMSE values of all items of dependent variables (B, F, D)?
--Should I evaluate the items in each dependent variable separately?
--Should I evaluate all items?
thanks for the help
![image](https://user-images.githubusercontent.com/114403335/192264638-cc82c3b0-7195-4feb-9cb4-6ce6d702991d.png)

**Comment by NicholasDanks** [comment]
Dear Isa,

Thank you very much for this question. However, the FB group is for about plied questions while GitHub is only for coding issues. Could you post it in Facebook and close this issue?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: isagul233 ***@***.***>
Sent: Monday, September 26, 2022 12:25:02 PM
To: sem-in-r/seminr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sem-in-r/seminr] predictive power assessment in SEMinR (Issue #312)


Hello everyone.
I m testing a model like below. I will evaluate the predictive power of my model.
--Should I evaluate out-of-sample LM-RMSE values of all items of dependent variables (B, F, D)?
--Should I evaluate the items in each dependent variable separately?
--Should I evaluate all items?
thanks for the help
[image]<https://user-images.githubusercontent.com/114403335/192264638-cc82c3b0-7195-4feb-9cb4-6ce6d702991d.png>

**Comment by isagul233** [comment]
Sorry, my problem was posted on FB.

**Comment by isagul233** [comment]
Sorry, my problem was posted on FB. Thanks.

Nicholas Danks ***@***.***>, 26 Eyl 2022 Pzt, 22:09 tarihinde
şunu yazdı:
