### ISSUE TITLE
Sobel Test For Simple Mediation

### ISSUE THREAD

**Issue by sandeepdey98** [sem-in-r/seminr#316]
Dear Prof. Ray ji, Dear Nicholas,
I have a simple mediation model  (A->B->C type) in my doctoral thesis. While I have used seminr extensively for other aspects of my doctoral work, I just wanted to get your 2 cents on how to conduct a sobel test. Any ideas or leads will be helpful.

thanks and regards,

**Comment by soumyaray** [comment]
Dear Sandeep, this would be a great question to post on our Facebook group for SEMinR where other users congregate and would find your question helpful! Please repost at: https://www.facebook.com/groups/seminr/

We will only use these issues on Github for bug reporting. See over at our FB group!
(if you do not use FB, kindly contact me directly via email)
