### ISSUE TITLE
Missing Value Error when estimating the model

### ISSUE THREAD

**Issue by PrabathRanatunga** [sem-in-r/seminr#336]
This is my code and I receive the following error when run the code. My analysis used higher-order constructs. Please help me. 

install.packages("seminr")
library(seminr)

# Loading CSV file
EML_JS_OC_data <- read.csv(file = "Tepuli Data Sheet 2.csv", header = TRUE, sep = ",")
head(EL_JS_OC_data)

# Create measurement model, Emotional Labour, Job Satisfaction, Organizational commitment
EML_JS_OC_mm <- constructs(
  composite("EML1", multi_items("EML1_", 1:16)),
  composite("EML2", multi_items("EML2_", 1:9)),
  composite("EML3", multi_items("EML3_", 1:3)),
  composite("EML4", multi_items("EML4_", 1:3)),
  higher_composite("EML", c("EML1","EML2", "EML3", "EML4"), method = "two stage"),
  
  composite("JS1", multi_items("JS1_", 1:4)),
  composite("JS2", multi_items("JS2_", 1:4)),
  composite("JS3", multi_items("JS3_", 1:4)),
  composite("JS4", multi_items("JS4_", 1:4)),
  composite("JS5", multi_items("JS5_", 1:4)),
  composite("JS6", multi_items("JS6_", 1:4)),
  composite("JS7", multi_items("JS7_", 1:4)),
  composite("JS8", multi_items("JS8_", 1:4)),
  composite("JS9", multi_items("JS9_", 1:4)),
  higher_composite("JS", c("JS1","JS2", "JS3", "JS4", "JS5", "JS6", "JS7", "JS8", "JS9"), method = "two stage"),

  composite("OC1", multi_items("OC1_", 1:8)),
  composite("OC2", multi_items("OC2_", 1:8)),
  composite("OC3", multi_items("OC3_", 1:8)) )
  higher_composite("OC", c("OC1","OC2", "OC3" ), method = "two stage")))

# Create structural model
EML_JS_OC_sm <- relationships(
  paths(from = c("EML"), to = c("JS")),
        paths(from = c("EML"), to = c("OC")),
              paths(from = c("JS"), to = c("OC")))

# Estimate the Model
EML_JS_OC_PLS_model <- estimate_pls(data = EML_JS_OC_data,
                                   measurement_model = EML_JS_OC_mm,
                                   structural_model  = EML_JS_OC_sm,
                                   inner_weights = path_weighting,
                                   missing = mean_replacement,
                                   missing_value = "-99")

Generating the seminr model
Generating the seminr model
All 355 observations are valid.
Error in if ((mmMatrix[mmMatrix[, "construct"] == construct, "type"][1] ==  : 
  missing value where TRUE/FALSE needed

**Comment by soumyaray** [comment]
Greetings, please try `method = two_stage` instead of `method = "two stage` and see if that resolves some issues?

**Comment by PrabathRanatunga** [comment]
Thanks for the prompt reply. I tried method = two_stage. However, it doesn't work and the following error comes. 

Error: unexpected symbol in:
"  composite("EML4", multi_items("EML4_", 1:3)),
  higher_composite("EML", c("EML1","EML2", "EML3", "EML4"), method = two stage"

**Comment by soumyaray** [comment]
greetings, please see my instructions again: it should be `method = two_stage`.  Note the underscore between the words `two` and `stage`.
