### ISSUE TITLE
interaction warning for PLSc adjustment

### ISSUE THREAD

**Issue by soumyaray** [sem-in-r/seminr#37]
Following warning shows up even if model does not include `reflective` constructs:
```
Models with interactions cannot be estimated as PLS consistent
and therefore no adjustment for PLS consistent has been made
For a PLS consistent simple interaction model please refer to PLSc_interact() function
```

Example: run demo/seminr_contained.R

Should only show up for models with reflective constructs involved in interactions

**Comment by NicholasDanks** [comment]
Addressed in branch CRAN_submission_prep
