### ISSUE TITLE
Construct descriptives in summary

### ISSUE THREAD

**Issue by soumyaray** [sem-in-r/seminr#54]
Either add construct descriptives in summary, or show how to get them in the vignette/manuals

**Comment by NicholasDanks** [comment]
Why do we need construct descriptives? Which descriptives specifically?

**Comment by NicholasDanks** [comment]
- [ ] Also item descriptives
- [ ] kurtosis
- [ ] observation sd
- [ ] min, max, median
- [ ] skewness
- [ ] item correlations
