### ISSUE TITLE
in rhoC_AVE() error in if_else()

### ISSUE THREAD

**Issue by NicholasDanks** [sem-in-r/seminr#58]
} else {
dgr[i,1] <- NA
dgr[i,2] <- sum(x^2)/length(x)

should be:

ind <- which(x!=0)
x <- x[ind]
dgr[i,1] <- NA
dgr[i,2] <- sum(x^2)/length(x)

**Comment by soumyaray** [comment]
the coding markdown isn't working — can you try fixing it?  also, what's the issue exactly?

**Comment by NicholasDanks** [comment]
For fully common-factor specified models, the else portion of the if_else statement is called.
The vector x contains loadings. 
This vector should be indexed to return only the loadings of the appropriate items on the appropriate construct.
Otherwise an incorrect mean is calculated in the final line
