### ISSUE TITLE
Explicitly define dependencies in DESCRIPTION

### ISSUE THREAD

**Issue by NicholasDanks** [sem-in-r/seminr#59]
An issue to help install 'seminr' package.

install.packages('seminr', dependencies=TRUE, type="source")

perhaps SEMinR's DESCRIPTION file needs the Depends: … line to include parallel or any other packages needed. instead of Imports: ...

**Comment by soumyaray** [comment]
Where's the online article/issue discussing this?

**Comment by NicholasDanks** [comment]
This is only problematic for OLD versions of R. 
"Imports" is safer than "Depends" (and also makes a package using it a 'better citizen' with respect to other packages that do use "Depends").

A "Depends" directive attempts to ensure that a function from another package is available by attaching the other package to the main search path (i.e. the list of environments returned by search()). This strategy can, however, be thwarted if another package, loaded later, places an identically named function earlier on the search path. Chambers (in SoDA) uses the example of the function "gam", which is found in both the gam and mgcv packages. If two other packages were loaded, one of them depending on gam and one depending on mgcv, the function found by calls to gam() would depend on the order in which they those two packages were attached. Not good.

An "Imports" directive places the imported package in <imports:packageName> (searched immediately after <namespace:packageName>), instead of on the regular search path. If either one of the packages in the example above used the "Imports" mechanism, matters would be improved in two ways. (1) The package would itself gain control over which mgcv function is used. (2) By keeping the main search path clear of the imported objects, it would not even potentially break the other package's dependency on the other mgcv function.

This is why using namespaces is such a good practice, why it is now enforced by CRAN, and (in particular) why using "Imports" is safer than using "Depends".
