### ISSUE TITLE
compute_vif() function bug

### ISSUE THREAD

**Issue by NicholasDanks** [sem-in-r/seminr#65]
compute_vif() function cannot handle construct names with a space. eg "Intention Purchase" is not accepted, but "IntentionPurchase" is accepted.
This bug arises from the use of paste() in the formula for lm
```
compute_vif <- function(target, predictors, model_data) {
  independents_regr <- stats::lm(paste(target," ~."),
                                 data = as.data.frame(model_data[,predictors]))

  r_squared <- summary(independents_regr)$r.squared
  1/(1 - r_squared)
}
```

Add a test for constructs with spaces in name

**Comment by soumyaray** [comment]
@NicholasDanks should i address this or you?  please assign me if you want me to patch it.

**Comment by NicholasDanks** [comment]
@soumyaray No I'll get it in my current branch.

**Comment by NicholasDanks** [comment]
Addressed and tests added
