### ISSUE TITLE
HTMT bootstrap is fairly instable

### ISSUE THREAD

**Issue by NicholasDanks** [sem-in-r/seminr#75]
The p and t values for bootstrapped HTMT fluctuate largely (20%) between n = 500 bootstraps

**Comment by soumyaray** [comment]
how about if n=2000 or 3000?

**Comment by NicholasDanks** [comment]
boots = 2000
```
HTMT t-values:
             Image Expectation Quality Value Satisfaction Complaints Loyalty
Image            .       0.867    1.83  5.03         2.48       7.48   1.195
Expectation      .           .    1.20  3.29         1.25       6.15   1.619
Quality          .           .       .  4.43         1.52       7.69   2.579
Value            .           .       .     .         3.43       7.83   2.002
Satisfaction     .           .       .     .            .       6.94   0.341
Complaints       .           .       .     .            .          .   4.596
Loyalty          .           .       .     .            .          .       .
```

**Comment by soumyaray** [comment]
perhaps we can leave a warning message about HTMT if boots < 2000?

**Comment by soumyaray** [comment]
Is this resolvable with a warning message for boots < 2000?  Not sure if warning should go in bootstrapping function or in print.summary function for HTMT.

**Comment by NicholasDanks** [comment]
This problem is due to the possibility that HTMT can create NAs when taking the square root of a negative number. The implemented solution is to take the absolute values of correlations before meaning the correlations in the formula. This normalizes the formula between 0 - 1 and does not affect the meaning of HTMT. 
In bootstrap subsamples where the correlations can vary wildly this will turn up.

**Comment by NicholasDanks** [comment]
@soumyaray close issue?

**Comment by NicholasDanks** [comment]
We assume typical unidimensionality of reflective constructs for which HTMT is only applicable. In these cases, all items should load onto the construct in the same direction. If they don't, this might have specific reasons like reverse coded items in most of the situations. If we would treat the resulting negative correlations indeed as negative, HTMT would not be correct. Of course, this assumes that constructs are correctly specified and negative correlations are intentional. On the contrary, our version of HTMT would be incorrect for missspecified constructs with small mixed correlations/loadings. However, those constructs may not pass conventional reliability tests and thus discriminant validity might not be meaningful anyways. 
We had to make a choice and found this way more plausible.

In addition, summing negative and positive correlations may entail a negative result for one of the average monotrait-heteromethod correlations. However, if one of two monotrait-heteromethod correlation values is negative, it is not possible to compute the geometric mean (i.e., because we have a negative result under the square root). A software implementation also needs to deal with this situation (either by our changes or by reporting an error).
